package com.mercurio.lms.expedicao.edi.swt.action;

import java.util.Map;

import com.mercurio.adsm.framework.report.ReportExecutionManager;
import com.mercurio.lms.expedicao.edi.report.ReportLogProcessamentoEdiService;

/**
 * Generated by: ADSM ActionGenerator
 *
 * Não inserir documentação após ou remover a tag do XDoclet a seguir.
 * O valor do <code>id</code> informado abaixo deve ser utilizado para referenciar este serviço.
 * @spring.bean id="lms.expedicao.edi.swt.emitirLogProcessamentoEdiAction"
 */
public class EmitirLogProcessamentoEdiAction {

	private ReportExecutionManager reportExecutionManager;
	private ReportLogProcessamentoEdiService reportLogProcessamentoEdiService;
	
	public String execute(Map parameters) throws Exception{
		return reportExecutionManager.generateReportLocator(reportLogProcessamentoEdiService, parameters);
	}

	public void setreportLogProcessamentoEdiService(ReportLogProcessamentoEdiService reportLogProcessamentoEdiService) {
		this.reportLogProcessamentoEdiService = reportLogProcessamentoEdiService;
	}

	public void setReportExecutionManager(ReportExecutionManager reportExecutionManager) {
		this.reportExecutionManager = reportExecutionManager;
	}
}