package com.mercurio.lms.sim;

public interface ConstantesSim {

	Short CD_MERCADORIA_ENTREGA_EFETUADA = Short.valueOf("1");
	Short CD_MERCADORIA_CANCELADA = Short.valueOf("25");	
	Short CD_MERCADORIA_EM_CARREGAMENTO_ENTREGA = Short.valueOf("29");
	Short CD_MERCADORIA_EM_CARREGAMENTO_VIAGEM = Short.valueOf("30");
	Short CD_MERCADORIA_AGUARDANDO_SAIDA_PORTARIA = Short.valueOf("26");
	Short CD_MERCADORIA_AGUARDANDO_SAIDA_VIAGEM = Short.valueOf("31");
	Short CD_MERCADORIA_AGUARDANDO_SAIDA_ENTREGA = Short.valueOf("32");	
	Short CD_MERCADORIA_RETORNADA_EM_DESCARGA = Short.valueOf("33");
	Short CD_MERCADORIA_EM_DESCARGA = Short.valueOf("34");
	Short CD_MERCADORIA_NO_TERMINAL_AGUARDANDO_EMISSAO_DOCTO = Short.valueOf("36");
	Short CD_MERCADORIA_RETORNADA_AGUARDANDO_DESCARGA = Short.valueOf("37");
	Short CD_MERCADORIA_AGUARDANDO_DESCARGA = Short.valueOf("38");
	Short CD_MERCADORIA_CLIENTE_INDENIZADO = Short.valueOf("39");
	Short CD_MERCADORIA_AGUARDANDO_EMBARQUE = Short.valueOf("44");
	Short CD_MERCADORIA_AGUARDANDO_EMBARQUE_CIA_AEREA = Short.valueOf("55");
	Short CD_MERCADORIA_EM_VIAGEM_AEREA = Short.valueOf("2");
	
	Short CD_MERCADORIA_RECUSA_EM_TRANSITO = Short.valueOf("69");
	Short CD_MERCADORIA_EXTRAVIADA = Short.valueOf("70");
	Short CD_MERCADORIA_NO_TERMINAL = Short.valueOf("24");
	Short CD_MERCADORIA_NO_TERMINAL_PROGRAMADA_ROTA_VIAGEM = Short.valueOf("28");
	Short CD_MERCADORIA_NO_TERMINAL_PROGRAMADA_ROTA_ENTREGA = Short.valueOf("43");
	Short CD_MERCADORIA_NO_TERMINAL_MERCADORIA_RETORNADA = Short.valueOf("35");
	Short CD_MERCADORIA_COLETA_REALIZADA_NO_AEROPORTO = Short.valueOf("101");
	
	Short CD_MERCADORIA_DEVOLVIDA_REMENTENTE = Short.valueOf("53");
	Short CD_MERCADORIA_REFATURADA = Short.valueOf("54");
	
	Short CD_MERCADORIA_SINISTRADA = Short.valueOf("7");
	Short CD_MERCADORIA_PROCESSO_ENCERRADO_SEGURO_CLIENTE = Short.valueOf("67");
	Short CD_MERCADORIA_CTRC_MIGRADO_FATURAMENTO = Short.valueOf("999");
	
	String TP_EVENTO_PREVISTO = "P";
	String TP_EVENTO_REALIZADO = "R";
	
	String DOCTO_ATIVO = "A";
	String DOCTO_INATIVO = "I";

	/* Tipos de Scan */
	String TP_SCAN_FISICO = "SF";
	String TP_SCAN_LMS = "LM";
	String TP_SCAN_CASCADE = "CS";
	String TP_DESCARGA_SORTER = "SS";
	
	/*Lista de codigos de evento utilizados no LMS*/
	Short EVENTO_DOCUMENTO_DIGITADO = Short.valueOf("1");
	Short EVENTO_DOCUMENTO_EMITIDO = Short.valueOf("6");
	Short EVENTO_DOCUMENTO_REENTREGA_EMITIDO = Short.valueOf("7");
	Short EVENTO_DOCUMENTO_DEVOLUCAO_EMITIDO = Short.valueOf("8");
	Short EVENTO_DOCUMENTO_COMPLEMENTO_EMITIDO = Short.valueOf("9");

	Short EVENTO_CONHECIMENTO_SUBSTITUTO_EMITIDO = Short.valueOf("312");
	Short EVENTO_DOCUMENTO_REFATURA_EMITIDO = Short.valueOf("10");
	Short EVENTO_DATA_PREVISTA = Short.valueOf("11");
	Short EVENTO_DOCUMENTO_CANCELADO = Short.valueOf("12");
	Short EVENTO_MANIFESTO_EMITIDO = Short.valueOf("13");
	Short EVENTO_MANIFESTO_CANCELADO = Short.valueOf("14");
	Short EVENTO_AWB_EMITIDO = Short.valueOf("15");
	Short EVENTO_DOCUMENTO_EMITIDO_SEM_LOCALIZACAO = Short.valueOf("18");
	Short EVENTO_DOCUMENTO_ACERTADO = Short.valueOf("19");

	Short EVENTO_EMISSAO_CARTA_CORRECAO_CRT = Short.valueOf("20");
	Short EVENTO_ENTREGA = Short.valueOf("21");
	Short EVENTO_MERCADORIA_SENDO_ENTREGUE = Short.valueOf("22");
	Short EVENTO_VINCULACAO_RV = Short.valueOf("23");
	
	Short EVENTO_INICIO_CARREGAMENTO_ENTREGA = Short.valueOf("24");
	Short EVENTO_INICIO_CARREGAMENTO_VIAGEM = Short.valueOf("25");
	Short EVENTO_FIM_CARREGAMENTO_VIAGEM = Short.valueOf("26");
	Short EVENTO_FIM_CARREGAMENTO_ENTREGA = Short.valueOf("27");
	
	Short EVENTO_INICIO_DESCARGA_ENTREGA = Short.valueOf("28");
	Short EVENTO_INICIO_DESCARGA_VIAGEM = Short.valueOf("29");

	Short EVENTO_DESCARGA_CONCLUIDA = Short.valueOf("30");
	Short EVENTO_FIM_DESCARGA = Short.valueOf("31");
	Short EVENTO_AGUARDANDO_SAIDA_COLETA_ENTREGA = Short.valueOf("32");
	Short EVENTO_CANCELAMENTO_DESCARGA_ENTREGA_RETORNADA = Short.valueOf("33");
	Short EVENTO_CANCELAMENTO_DESCARGA_ENTREGA = Short.valueOf("34");
	Short EVENTO_GERACAO_RECIBO_INDENIZACAO = Short.valueOf("35");
	Short EVENTO_LIBERAR_PGTO_RIM = Short.valueOf("36");
	Short EVENTO_CANCELAR_LIBERACAO_RIM = Short.valueOf("37");
	Short EVENTO_CLIENTE_INDENIZADO = Short.valueOf("38");
	Short EVENTO_LIBERACAO = Short.valueOf("89");
	
	Short EVENTO_MERCADORIA_DISPOSICAO = Short.valueOf("39");
	Short EVENTO_MERCADORIA_APREENDIDA = Short.valueOf("40");
	Short EVENTO_AGUARDANDO_EMBARQUE_PRE_MANIFESTO = Short.valueOf("44");
	Short EVENTO_CARTA_MERCADORIA_DISPOSICAO = Short.valueOf("48");
	Short EVENTO_COMUNICADO_APREENSAO_ENVIADO = Short.valueOf("49");

	Short EVENTO_MDA_EMITIDA = Short.valueOf("50");
	Short EVENTO_CANCELAMENTO_MDA = Short.valueOf("51"); 
	Short EVENTO_REGISTRAR_RECEBIMENTO_MDA = Short.valueOf("52");
	Short EVENTO_CARTA_OCORRENCIA_SE = Short.valueOf("53");
	Short EVENTO_CARTA_RETIFICACAO_OCORRENCIA_SE = Short.valueOf("54");
	Short EVENTO_SAIDA_PORTARIA_EMVIAGEM = Short.valueOf("55");
	Short EVENTO_SAIDA_PORTARIA_EMROTA = Short.valueOf("56");
	Short EVENTO_CHEGADA_PORTARIA_MR_AD = Short.valueOf("57");
	Short EVENTO_CHEGADA_PORTARIA_EF = Short.valueOf("58");

	Short EVENTO_ENTRADA_CHECK_IN = Short.valueOf("60");
	Short EVENTO_PRE_MANIFESTO_VIAGEM_EMITIDO = Short.valueOf("61");
	Short EVENTO_PRE_MANIFESTO_ENTREGA_EMITIDO = Short.valueOf("62");
	Short EVENTO_RETIRADO_PRE_MANIFESTO_VIAGEM = Short.valueOf("63");
	Short EVENTO_PREVISAO_CHEGADA = Short.valueOf("66");

	Short EVENTO_SAIDA_PORTARIA_DESL_EMBAQ = Short.valueOf("84");
	Short EVENTO_ENTREGA_REALIZADA_AEROPORTO = Short.valueOf("85");  
	Short EVENTO_RETIRADO_PRE_MANIFESTO_ENTREGA = Short.valueOf("86");
	Short EVENTO_CANCELAMENTO_RIM = Short.valueOf("88");
	Short EVENTO_ROTA_COLETA_AERO = Short.valueOf("401");
	Short EVENTO_CANCELA_ROTA_COLETA_AERO = Short.valueOf("405");

	Short EVENTO_LIBERACAO_MERCADORIA_DEVOLVIDA_REM = Short.valueOf("90");
	Short EVENTO_MERCADORIA_DEVOLVIDA_REM = Short.valueOf("91");
	Short EVENTO_CANCELAR_PGTO_RIM = Short.valueOf("99");

	Short EVENTO_INFORMAR_PGTO_RIM = Short.valueOf("100");
	Short EVENTO_AGENDAMENTO = Short.valueOf("106");
	Short EVENTO_REAGENDADO = Short.valueOf("107");
	Short EVENTO_CANCELAMENTO = Short.valueOf("108");	
	Short EVENTO_CANCELAMENTO_AGENDAMENTO = Short.valueOf("109");	

	Short EVENTO_CANCELAMENTO_VINCULACAO_RV = Short.valueOf("110");
	Short EVENTO_REAGENDADO_2 = Short.valueOf("111");
	Short EVENTO_CANCELAMENTO_FIM_CARREGAMENTO = Short.valueOf("112");
	Short EVENTO_RNC_ABERTA = Short.valueOf("113");
	Short EVENTO_RNC_ENCERRADA = Short.valueOf("114");
	Short EVENTO_MANIFESTO_EMITIDO_PARCEIRA = Short.valueOf("115");
	Short EVENTO_MANIFESTO_ENTREGUE_PARCEIRA = Short.valueOf("116");

	Short EVENTO_CANCELAMENTO_CAREGAMENTO_VIAGEM = Short.valueOf("121");
	Short EVENTO_CANCELAMENTO_CAREGAMENTO_COLETA_ENTREGA = Short.valueOf("122");
	Short EVENTO_CANCELAMENTO_INICIO_CARREGAMENTO_ENTREGA = Short.valueOf("123");
	Short EVENTO_CANCELAMENTO_INICIO_CARREGAMENTO_VIAGEM = Short.valueOf("124");
	
	Short EVENTO_FIM_DESCARGA_SEM_MUDAR_LOCALIZACAO = Short.valueOf("125");
	
	Short EVENTO_MANIFESTO_CANCELAR = Short.valueOf("126");
	
	Short EVENTO_CHEGADA_PORTARIA_AD = Short.valueOf("130");
	Short EVENTO_GERACAO_RIM_SEM_LOCALIZACAO = Short.valueOf("132");
	Short EVENTO_CANCELAMENTO_RIM_SEM_LOCALIZACAO = Short.valueOf("133");
	
	Short EVENTO_ENCONTRADO = Short.valueOf("134");
	Short EVENTO_ESCANEADO = Short.valueOf("135");
	Short EVENTO_UNITIZADO = Short.valueOf("138"); 
	Short EVENTO_DESUNITIZADO = Short.valueOf("139");
	Short EVENTO_EXTRAVIADO = Short.valueOf("140");
	Short EVENTO_IMPRESSAO_ETIQUETA = Short.valueOf("141");
	Short EVENTO_ALOCADO = Short.valueOf("144");
	Short EVENTO_DESALOCADO = Short.valueOf("145");
	
	Short EVENTO_CANCELAR_PGTO_RIM_SEM_LOCALIZACAO = Short.valueOf("202");
	Short EVENTO_REALIZAR_COLETA_NO_AEROPORTO = Short.valueOf("402");
		
}
