package com.mercurio.lms.vol.action;

import java.util.List;
import java.util.Map;

import com.mercurio.adsm.framework.model.CrudAction;
import com.mercurio.adsm.framework.model.ResultSetPage;
import com.mercurio.adsm.framework.util.FilterList;
import com.mercurio.adsm.framework.util.TypedFlatMap;
import com.mercurio.lms.contratacaoveiculos.model.MeioTransporte;
import com.mercurio.lms.contratacaoveiculos.model.service.MeioTransporteService;
import com.mercurio.lms.vol.model.service.GerencialService;


/**
 * Generated by: ADSM ActionGenerator
 *  
 * Não inserir documentação após ou remover a tag do XDoclet a seguir.
 * O valor do <code>id</code> informado abaixo deve ser utilizado para referenciar este serviço.
 * @spring.bean id="lms.vol.gerencialEventosAction"
 * 					
 */

public class GerencialEventosAction extends CrudAction {
	
	private GerencialService gerencialService;
	private MeioTransporteService meioTransporteService;
	
	public ResultSetPage findPaginatedEventos(TypedFlatMap criteria) {
		return getGerencialService().findPaginatedEventos(criteria);
	}
	public Integer getRowCountEventos(TypedFlatMap criteria) {
		return getGerencialService().getRowCountEventos(criteria);
	}
	
	public GerencialService getGerencialService() {
		return gerencialService;
	}

	public void setGerencialService(GerencialService gerencialService) {
		this.gerencialService = gerencialService;
	}	

	public List findLookupMeioTransporte(Map criteria) {
    	FilterList filter = new FilterList(getMeioTransporteService().findLookup(criteria)) {
			public Map filterItem(Object item) {
				MeioTransporte meioTransporte = (MeioTransporte)item;
    			TypedFlatMap typedFlatMap = new TypedFlatMap();
	    		typedFlatMap.put("idMeioTransporte", meioTransporte.getIdMeioTransporte());
		    	typedFlatMap.put("nrFrota",  meioTransporte.getNrFrota());
		    	typedFlatMap.put("nrIdentificador",  meioTransporte.getNrIdentificador());
				return typedFlatMap;
			}
    	};
    	return (List)filter.doFilter();
    }
	
	public MeioTransporteService getMeioTransporteService() {
		return meioTransporteService;
	}
	public void setMeioTransporteService(MeioTransporteService meioTransporteService) {
		this.meioTransporteService = meioTransporteService;
	}
}
