package com.mercurio.lms.edi.util;


public interface ConstantesPdf2HashMap {

	//DIVISAO DO PDF
	String DESTINATARIO_REMETENTE = "DESTINATÁRIO/REMETENTE";
	String FATURA_DUPLICATA = "FATURA / DUPLICATA";
	String CALCULO_IMPOSTO = "CÁLCULO DO IMPOSTO";
	String TRANSPORTADOR_VOLUMES_TRANSPORTADOS = "TRANSPORTADOR/VOLUMES TRANSPORTADOS";
	String DADOS_PRODUTOS_SERVICOS = "DADOS DOS PRODUTOS/SERVIÇOS";
	String DADOS_ADICIONAIS = "DADOS ADICIONAIS";
	
	//CABECALHO - DADOS DO EMITENTE
	String LINHA_PONTILHADA_CABECALHO = "- - -";
	String ENTRADA_SAIDA = "ENTRADA_SAIDA"; 
	String NUMERO_NFE = "Nº"; 
	String SERIE_NFE = "SÉRIE";
	String FOLHA = "FOLHA";
	String RAZAO_SOCIAL_EMITENTE = "RAZÃO SOCIAL EMITENTE";
	String CNPJ_EMITENTE = "CNPJ";
	String INSCRICAO_ESTADUAL_EMITENTE_TO_READ_FROM_PDF = "INSCRIÇÃO ESTADUAL";
	String INSCRICAO_ESTADUAL_EMITENTE_TO_PUT_AND_GET_MAP = "INSCRICAO_ESTADUAL_EMITENTE";
	String INSCRICAO_ESTADUAL_SUBSTITUICAO_TRIB_EMITENTE = "INSC. EST. SUBST. TRIB.";
	String NATUREZA_OPERACAO_EMITENTE = "NATUREZA DA OPERAÇÃO";
	String CHAVE_ACESSO = "CHAVE DE ACESSO";
	String DADOS_NFE = "DADOS DA NF-e";
	String ENDERECO_EMITENTE_TO_READ_FROM_PDF = "ENDEREÇO";
	String ENDERECO_EMITENTE_TO_PUT_AND_GET_MAP = "ENDERECO_EMITENTE";
	String BAIRRO_DISTRITO_EMITENTE_TO_READ_FROM_PDF = "BAIRRO/DISTRITO";
	String BAIRRO_DISTRITO_EMITENTE_TO_PUT_AND_GET_MAP = "BAIRRO_DISTRITO_EMITENTE";
	String CEP_EMITENTE_TO_READ_FROM_PDF = "CEP";
	String CEP_EMITENTE_TO_PUT_AND_GET_MAP = "CEP_EMITENTE";
	String MUNICIPIO_EMITENTE_TO_READ_FROM_PDF = "MUNICÍPIO";
	String MUNICIPIO_EMITENTE_TO_PUT_AND_GET_MAP = "MUNICIPIO_EMITENTE";
	String TELEFONE_EMITENTE = "TELEFONE_EMITENTE";
	String FAX_EMITENTE = "FAX_EMITENTE";
	String UF_EMITENTE_TO_READ_FROM_PDF = "UF";	
	String UF_EMITENTE_TO_PUT_AND_GET_MAP = "UF_EMITENTE";	
	
	//DESTINATARIO REMETENTE
	String NOME_RAZAO_SOCIAL_DESTINATARIO = "NOME/RAZÃO SOCIAL";
	String CNPJ_CPF_DESTINATARIO = "CNPJ/CPF";
	String DATA_EMISSAO = "DATA DA EMISSÃO";
	String ENDERECO_DESTINATARIO_TO_READ_FROM_PDF = "ENDEREÇO";
	String ENDERECO_DESTINATARIO_TO_PUT_AND_GET_MAP = "ENDERECO_REMETENTE";
	String BAIRRO_DISTRITO_DESTINATARIO_TO_READ_FROM_PDF = "BAIRRO/DISTRITO";
	String BAIRRO_DISTRITO_DESTINATARIO_TO_PUT_AND_GET_MAP = "BAIRRO_DISTRITO_REMETENTE";
	String CEP_DESTINATARIO_TO_READ_FROM_PDF = "CEP";
	String CEP_DESTINATARIO_TO_PUT_AND_GET_MAP = "CEP_REMETENTE";
	String DATA_ENTRADA_SAIDA = "DATA DE ENTRADA/SAÍDA";
	String MUNICIPIO_DESTINATARIO_TO_READ_FROM_PDF = "MUNICÍPIO";
	String MUNICIPIO_DESTINATARIO_TO_PUT_AND_GET_MAP = "MUNICIPIO_REMETENTE";
	String TELEFONE_FAX_DESTINATARIO = "TELEFONE/FAX";
	String UF_DESTINATARIO_TO_READ_FROM_PDF = "UF";
	String UF_DESTINATARIO_TO_PUT_AND_GET_MAP = "UF_REMETENTE";
	String INSCRICAO_ESTADUAL_DESTINATARIO_TO_READ_FROM_PDF = "INSCRIÇÃO ESTADUAL";
	String INSCRICAO_ESTADUAL_DESTINATARIO_TO_PUT_AND_GET_MAP = "INSCRICAO_ESTADUAL_REMETENTE";
	String HORA_SAIDA = "HORA DE SAÍDA";
	
	//CALCULO IMPOSTO
	String BASE_CALCULO_ICMS = "BASE CÁLCULO ICMS";
	String VALOR_ICMS = "VALOR DO ICMS";
	String BASE_CALCULO_ICMS_SUBSTITUICAO = "BASE CALCULO ICMS SUBSTITUICAO";
	String VALOR_ICMS_SUBSTITUICAO = "VALOR DO ICMS SUBSTITUICAO";
	String VALOR_TOTAL_PRODUTOS = "VALOR TOTAL DOS PRODUTOS";
	String VALOR_FRETE = "VALOR DO FRETE";
	String VALOR_SEGURO = "VALOR DO SEGURO";
	String DESCONTO = "DESCONTO";
	String OUTRAS_DESPESAS_ACESSORIAS = "OUTRAS DESPESAS ACESSORIAS";
	String VALOR_IPI = "VALOR DO IPI";
	String VALOR_TOTAL_NOTA = "VALOR TOTAL DA NOTA";
	
	//TRANSPORTADOR/VOLUMES TRANSPORTADOS
	String RAZAO_SOCIAL_TRANSPORTADOR = "RAZÃO SOCIAL";
	String FRETE_POR_CONTA = "FRETE POR CONTA";
	String CODIGO_ANTT = "CÓDIGO ANTT";
	String PLACA_VEICULO = "PLACA DO VEICULO"; 
	String UF_PLACA_VEICULO_TRANSPORTADOR_TO_READ_FROM_PDF = "UF";
	String UF_PLACA_VEICULO_TRANSPORTADOR_TO_PUT_AND_GET_MAP = "UF_TRANSPORTADOR";
	String CNPJ_CPF_TRANSPORTADOR = "CNPJ / CPF";
	String ENDERECO_TRANSPORTADOR_TO_READ_FROM_PDF = "ENDEREÇO";
	String ENDERECO_TRANSPORTADOR_TO_PUT_AND_GET_MAP = "ENDERECO_TRANSPORTADOR";
	String MUNICIPIO_TRANSPORTADOR_TO_READ_FROM_PDF = "MUNICÍPIO";
	String MUNICIPIO_TRANSPORTADOR_TO_PUT_AND_GET_MAP = "MUNICIPIO_TRANSPORTADOR";
	String UF_TRANSPORTADOR_TO_READ_FROM_PDF = "UF";
	String UF_TRANSPORTADOR_TO_PUT_AND_GET_MAP = "UF_TRANSPORTADOR";
	String INSCRICAO_ESTADUAL_TRANSPORTADOR_TO_READ_FROM_PDF = "INSCRIÇÃO ESTADUAL";
	String INSCRICAO_ESTADUAL_TRANSPORTADOR_TO_PUT_AND_GET_MAP = "INSCRICAO_ESTADUAL_TRANSPORTADOR";
	String QUANTIDADE_VOLUMES_TRANSPORTADOS = "QUANTIDADE";
	String ESPECIE_VOLUMES_TRANSPORTADOS = "ESPÉCIE";
	String MARCA_VOLUMES_TRANSPORTADOS = "MARCA";
	String NUMERO_VOLUMES_TRANSPORTADOS = "NUMERO";
	String PESO_BRUTO_VOLUMES_TRANSPORTADOS = "PESO BRUTO";
	String PESO_LIQUIDO_VOLUMES_TRANSPORTADOS = "PESO LÍQUIDO";
	
	//DADOS DOS PRODUTOS/SERVICOS
	
	//DADOS ADICIONAIS
	String ORDEM_COMPRA = "ORDEM DE COMPRA";
	String NFREG = "NFREG";
	
}
