package com.mercurio.lms.contasreceber.action;

import java.io.Serializable;
import java.util.List;

import com.mercurio.adsm.framework.model.CrudAction;
import com.mercurio.adsm.framework.model.ResultSetPage;
import com.mercurio.adsm.framework.util.TypedFlatMap;
import com.mercurio.lms.contasreceber.model.OcorrenciaBanco;
import com.mercurio.lms.contasreceber.model.service.OcorrenciaBancoService;

import com.mercurio.adsm.framework.annotations.ParametrizedAttribute;


/**
 * Generated by: ADSM ActionGenerator
 *  
 * Não inserir documentação após ou remover a tag do XDoclet a seguir.
 * O valor do <code>id</code> informado abaixo deve ser utilizado para referenciar este serviço.
 * @spring.bean id="lms.contasreceber.manterOcorrenciasRemessaRetornoBancosAction"
 */

public class ManterOcorrenciasRemessaRetornoBancosAction extends CrudAction {
	
	/** Cria a variável do tipo OcorrenciaBancoService*/
	private OcorrenciaBancoService ocorrenciaBancoService;
	
	/** Seta um novo objeto OcorrenciaBancoService na variável ocorrenciaBancoService, através da inversão de controle do Spring */
	public void setOcorrenciaBancoService(OcorrenciaBancoService ocorrenciaBancoService) {
		this.ocorrenciaBancoService = ocorrenciaBancoService;
	}
	
	/**
     * Método que busca as OcorrenciasBanco de acordo com os filtros passados
     * @param criteria
     * @return ResultSetPage
     */
	public ResultSetPage findPaginatedByOcorrenciaRemessaRetornoBancos(TypedFlatMap criteria){
		return ocorrenciaBancoService.findPaginatedByOcorrenciaRemessaRetornoBancos(criteria);
	}
	
	 /**
     * Método que retorna o número de registros de acordo com os filtros passados
     * @param criteria
     * @return
     */
	public Integer getRowCountByOcorrenciaRemessaRetornoBancos(TypedFlatMap criteria){
		return ocorrenciaBancoService.getRowCountByOcorrenciaRemessaRetornoBancos(criteria);
	}
	
	/**
	 *
	 */
	@ParametrizedAttribute(type = java.lang.Long.class)
    public void removeByIds(List ids) {
    	ocorrenciaBancoService.removeByIds(ids);
    }

    /**
     * Método responsável por carregar um pojo OcorrenciaBanco de acordo com o id passado por parâmetro
     * @param id
     * @return OcorrenciaBancos
     */
    public OcorrenciaBanco findById(Long id) {
		return ocorrenciaBancoService.findById(id);
	}

    /**
     * Método responsavel por excluir um OcorrenciaBanco de acordo com id passado por parâmetro
     * @param id
     */
	public void removeById(Long id) {
		ocorrenciaBancoService.removeById(id);
	}
    
    /**
     * Método responsável por inserir ou editar um pojo OcorrenciaBanco
     * @param bean
     * @return Serializable
     */
    public Serializable store(OcorrenciaBanco bean) {
    	return ocorrenciaBancoService.store(bean);
    }
}
