var documentoDocumentWidgetDefinitions = new Array();


/*Este js e especifico para a tela de incluir eventos de rastreabilidade dos documento de servico abaixo:
AWB,
CCA,
CRT,
CTO,
PED,
PEI,
MAE,
MAV,
MDA,
MIC,
MID,
NTT
*/

var CTR_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION = { 
								type:"CTR", 
								filial:{
									property:"filialByIdFilialOrigem", 
									idProperty:"idFilial", 
									criteriaProperty:"sgFilial", 
									service:"lms.municipios.filialService.findLookup", 
									actionServiceMethod:"findLookupFilialByDocumentoServico",
									url:"/municipios/manterFiliais.do",
									propertyMappings:[
										{ 
						 					modelProperty:"sgFilial", 
											criteriaProperty:"filialByIdFilialOrigem.sgFilial", 
											inlineQuery:true
										}, 
										{ 
						 					modelProperty:"empresa.tpEmpresa", 
											criteriaProperty:"empresa.tpEmpresa", 
											inlineQuery:true
										}, 
										{
											modelProperty:"sgFilial", 
											relatedProperty:"filialByIdFilialOrigem.sgFilial"
										},
										{ 
											modelProperty:"pessoa.nmFantasia", 
											relatedProperty:"filialByIdFilialOrigem.pessoa.nmFantasia"
										}
									]
								}, 
								documentNumber:{
									property:"conhecimento", 
									idProperty:"idDoctoServico", 
									criteriaProperty:"nrConhecimento", 
									service:"lms.expedicao.conhecimentoService.findLookup", 
									actionServiceMethod:"findLookupDocumentoDocumentNumberCTR",
									url:"/expedicao/pesquisarConhecimento.do", 
									maxChars:"8", 
									mask:"00000000",
									propertyMappings:[
										{ 
											modelProperty:"nrConhecimento", 
											criteriaProperty:"conhecimento.nrConhecimento",
											inlineQuery:true
										},
										{ 
											modelProperty:"tpDocumentoServico", 
											criteriaProperty:"tpDocumentoServico",
											inlineQuery:true
										},
										{ 
											modelProperty:"nrConhecimento", 
											relatedProperty:"nrDocumento",
											disabled:false
										},
										{ 
											modelProperty:"nrConhecimento", 
											relatedProperty:"conhecimento.nrConhecimento"
										},	
										{ 
											modelProperty:"filialByIdFilialOrigem.idFilial", 
											criteriaProperty:"filialByIdFilialOrigem.idFilial",
											inlineQuery:true
										},
										{ 
											modelProperty:"filialByIdFilialOrigem.sgFilial", 
											criteriaProperty:"filialByIdFilialOrigem.sgFilial",
											inlineQuery:false
										},
										{ 
											modelProperty:"filialByIdFilialOrigem.pessoa.nmFantasia", 
											criteriaProperty:"filialByIdFilialOrigem.pessoa.nmFantasia",
											inlineQuery:false
										},										
										{ 
											modelProperty:"filialByIdFilialOrigem.sgFilial", 
											relatedProperty:"filialByIdFilialOrigem.sgFilial",
											blankFill:false											
										},
										{ 
											modelProperty:"filialByIdFilialOrigem.idFilial", 
											relatedProperty:"filialByIdFilialOrigem.idFilial",
											blankFill:false											
										},
										{ 
											modelProperty:"filialByIdFilialOrigem.pessoa.nmFantasia", 
											relatedProperty:"filialByIdFilialOrigem.pessoa.nmFantasia",
											blankFill:false
										}
									]
								}
							};
documentoDocumentWidgetDefinitions[documentoDocumentWidgetDefinitions.length] = CTR_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION;

var CTE_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION = { 
		type:"CTE", 
		filial:{
			property:"filialByIdFilialOrigem", 
			idProperty:"idFilial", 
			criteriaProperty:"sgFilial", 
			service:"lms.municipios.filialService.findLookup", 
			actionServiceMethod:"findLookupFilialByDocumentoServico",
			url:"/municipios/manterFiliais.do",
			propertyMappings:[
			                  { 
			                	  modelProperty:"sgFilial", 
			                	  criteriaProperty:"filialByIdFilialOrigem.sgFilial", 
			                	  inlineQuery:true
			                  }, 
			                  { 
			                	  modelProperty:"empresa.tpEmpresa", 
			                	  criteriaProperty:"empresa.tpEmpresa", 
			                	  inlineQuery:true
			                  }, 
			                  {
			                	  modelProperty:"sgFilial", 
			                	  relatedProperty:"filialByIdFilialOrigem.sgFilial"
			                  },
			                  { 
			                	  modelProperty:"pessoa.nmFantasia", 
			                	  relatedProperty:"filialByIdFilialOrigem.pessoa.nmFantasia"
			                  }
			                  ]
		}, 
		documentNumber:{
			property:"conhecimento", 
			idProperty:"idDoctoServico", 
			criteriaProperty:"nrConhecimento", 
			service:"lms.expedicao.conhecimentoService.findLookup", 
			actionServiceMethod:"findLookupDocumentoDocumentNumberCTE",
			url:"/expedicao/pesquisarConhecimento.do", 
			maxChars:"8", 
			mask:"00000000",
			propertyMappings:[
			                  { 
			                	  modelProperty:"nrConhecimento", 
			                	  criteriaProperty:"conhecimento.nrConhecimento",
			                	  inlineQuery:true
			                  },
			                  { 
			                	  modelProperty:"tpDocumentoServico", 
			                	  criteriaProperty:"tpDocumentoServico",
			                	  inlineQuery:true
			                  },
			                  { 
			                	  modelProperty:"nrConhecimento", 
			                	  relatedProperty:"nrDocumento",
			                	  disabled:false
			                  },
			                  { 
			                	  modelProperty:"nrConhecimento", 
			                	  relatedProperty:"conhecimento.nrConhecimento"
			                  },	
			                  { 
			                	  modelProperty:"filialByIdFilialOrigem.idFilial", 
			                	  criteriaProperty:"filialByIdFilialOrigem.idFilial",
			                	  inlineQuery:true
			                  },
			                  { 
			                	  modelProperty:"filialByIdFilialOrigem.sgFilial", 
			                	  criteriaProperty:"filialByIdFilialOrigem.sgFilial",
			                	  inlineQuery:false
			                  },
			                  { 
			                	  modelProperty:"filialByIdFilialOrigem.pessoa.nmFantasia", 
			                	  criteriaProperty:"filialByIdFilialOrigem.pessoa.nmFantasia",
			                	  inlineQuery:false
			                  },										
			                  { 
			                	  modelProperty:"filialByIdFilialOrigem.sgFilial", 
			                	  relatedProperty:"filialByIdFilialOrigem.sgFilial",
			                	  blankFill:false											
			                  },
			                  { 
			                	  modelProperty:"filialByIdFilialOrigem.idFilial", 
			                	  relatedProperty:"filialByIdFilialOrigem.idFilial",
			                	  blankFill:false											
			                  },
			                  { 
			                	  modelProperty:"filialByIdFilialOrigem.pessoa.nmFantasia", 
			                	  relatedProperty:"filialByIdFilialOrigem.pessoa.nmFantasia",
			                	  blankFill:false
			                  }
			                  ]
		}
};
documentoDocumentWidgetDefinitions[documentoDocumentWidgetDefinitions.length] = CTE_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION;

var AWB_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION = {
								type:"AWB", 		
								filial:{
									property:"filialByIdFilialOrigem", 
									idProperty:"idFilial", 
									criteriaProperty:"sgFilial", 
									service:"lms.municipios.filialService.findLookup", 
									actionServiceMethod:"findLookupFilialByDocumentoServico",
									url:"/municipios/manterFiliais.do"
								}, 						
								documentNumber:{
									property:"awb", 
									idProperty:"idAwb", 
									criteriaProperty:"nrAwb", 
									service:"lms.expedicao.ctoInternacionalService.findLookup", 
									actionServiceMethod:"findLookupDocumentoDocumentNumberAWB",
									url:"/expedicao/consultarAWBs.do", 
									maxChars:"6", 
									mask:"000000",
									propertyMappings:[
										{
											modelProperty:"nrAwb", 
											criteriaProperty:"awb.nrAwb", 
											inlineQuery:true
										}, 
										{
											modelProperty:"nrAwb", 
											relatedProperty:"nrDocumento",
											disabled:false
										},
										{
											modelProperty:"nrAwb", 
											relatedProperty:"awb.nrAwb"
										}
									]
								}
							};
documentoDocumentWidgetDefinitions[documentoDocumentWidgetDefinitions.length] = AWB_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION;

var CCA_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION = {
								type:"CCA", 
								filial:{
									property:"filialByIdFilialOrigem", 
									idProperty:"idFilial", 
									criteriaProperty:"sgFilial", 
									service:"lms.municipios.filialService.findLookup", 
									actionServiceMethod:"findLookupFilialByDocumentoServico",
									url:"/municipios/manterFiliais.do",
									propertyMappings:[
										{ 
						 					modelProperty:"sgFilial", 
											criteriaProperty:"filialByIdFilialOrigem.sgFilial", 
											inlineQuery:true
										}, 
										{ 
						 					modelProperty:"empresa.tpEmpresa", 
											criteriaProperty:"empresa.tpEmpresa", 
											inlineQuery:true
										}, 
										{
											modelProperty:"sgFilial", 
											relatedProperty:"filialByIdFilialOrigem.sgFilial"
										},
										{ 
											modelProperty:"pessoa.nmFantasia", 
											relatedProperty:"filialByIdFilialOrigem.pessoa.nmFantasia"
										}
									]								
								}, 
								documentNumber:{
									property:"controleCarga", 
									idProperty:"idControleCarga", 
									criteriaProperty:"nrControleCarga", 
									service:"lms.expedicao.ctoInternacionalService.findLookup", 
									actionServiceMethod:"findLookupDocumentoDocumentNumberCCA",
									url:"/carregamento/manterControleCargas.do", 
									maxChars:"8", 
									mask:"00000000",
									propertyMappings:[
										{
											modelProperty:"nrControleCarga", 
											criteriaProperty:"controleCarga.nrControleCarga", 
											inlineQuery:true
										}, 
										{
											modelProperty:"nrControleCarga", 
											relatedProperty:"nrDocumento",
											disabled:false
										},
										{
											modelProperty:"nrControleCarga", 
											relatedProperty:"controleCarga.nrControleCarga"
										},
										{ 
											modelProperty:"filialByIdFilialOrigem.idFilial", 
											criteriaProperty:"filialByIdFilialOrigem.idFilial",
											inlineQuery:true
										},
										{ 
											modelProperty:"filialByIdFilialOrigem.sgFilial", 
											criteriaProperty:"filialByIdFilialOrigem.sgFilial",
											inlineQuery:false
										},
										{ 
											modelProperty:"filialByIdFilialOrigem.pessoa.nmFantasia", 
											criteriaProperty:"filialByIdFilialOrigem.pessoa.nmFantasia",
											inlineQuery:false
										},										
										{ 
											modelProperty:"filialByIdFilialOrigem.sgFilial", 
											relatedProperty:"filialByIdFilialOrigem.sgFilial",
											blankFill:false
										},
										{ 
											modelProperty:"filialByIdFilialOrigem.idFilial", 
											relatedProperty:"filialByIdFilialOrigem.idFilial",
											blankFill:false
										},
										{ 
											modelProperty:"filialByIdFilialOrigem.pessoa.nmFantasia", 
											relatedProperty:"filialByIdFilialOrigem.pessoa.nmFantasia",
											blankFill:false
										}
									]
								}
							};
documentoDocumentWidgetDefinitions[documentoDocumentWidgetDefinitions.length] = CCA_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION;

var CRT_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION = {
								type:"CRT", 
								filial:{
									property:"filialByIdFilialOrigem", 
									idProperty:"idFilial", 
									criteriaProperty:"sgFilial", 
									service:"lms.municipios.filialService.findLookup", 
									actionServiceMethod:"findLookupFilialByDocumentoServico",
									url:"/municipios/manterFiliais.do",
									propertyMappings:[
										{ 
						 					modelProperty:"sgFilial", 
											criteriaProperty:"filialByIdFilialOrigem.sgFilial", 
											inlineQuery:true
										}, 
										{ 
						 					modelProperty:"empresa.tpEmpresa", 
											criteriaProperty:"empresa.tpEmpresa", 
											inlineQuery:true
										}, 
										{
											modelProperty:"sgFilial", 
											relatedProperty:"filialByIdFilialOrigem.sgFilial"
										},
										{ 
											modelProperty:"pessoa.nmFantasia", 
											relatedProperty:"filialByIdFilialOrigem.pessoa.nmFantasia"
										}
									]
								}, 
								documentNumber:{
									property:"ctoInternacional", 
									idProperty:"idDoctoServico", 
									criteriaProperty:"nrCrt", 
									service:"lms.expedicao.ctoInternacionalService.findLookup", 
									actionServiceMethod:"findLookupDocumentoDocumentNumberCRT",
									url:"/expedicao/manterCRT.do", 
									maxChars:"6", 
									mask:"000000",
									propertyMappings:[
										{
											modelProperty:"nrCrt", 
											criteriaProperty:"ctoInternacional.nrCrt", 
											inlineQuery:true
										}, 
										{
											modelProperty:"nrCrt", 
											relatedProperty:"nrDocumento",
											disabled:false
										},
										{
											modelProperty:"nrCrt", 
											relatedProperty:"ctoInternacional.nrCrt"
										},
										{ 
											modelProperty:"filialByIdFilialOrigem.idFilial", 
											criteriaProperty:"filialByIdFilialOrigem.idFilial",
											inlineQuery:true
										},
										{ 
											modelProperty:"filialByIdFilialOrigem.sgFilial", 
											criteriaProperty:"filialByIdFilialOrigem.sgFilial",
											inlineQuery:false
										},
										{ 
											modelProperty:"filialByIdFilialOrigem.pessoa.nmFantasia", 
											criteriaProperty:"filialByIdFilialOrigem.pessoa.nmFantasia",
											inlineQuery:false
										},										
										{ 
											modelProperty:"filialByIdFilialOrigem.sgFilial", 
											relatedProperty:"filialByIdFilialOrigem.sgFilial",
											blankFill:false											
										},
										{ 
											modelProperty:"filialByIdFilialOrigem.idFilial", 
											relatedProperty:"filialByIdFilialOrigem.idFilial",
											blankFill:false											
										},
										{ 
											modelProperty:"filialByIdFilialOrigem.pessoa.nmFantasia", 
											relatedProperty:"filialByIdFilialOrigem.pessoa.nmFantasia",
											blankFill:false											
										}
									]
								}
							};
documentoDocumentWidgetDefinitions[documentoDocumentWidgetDefinitions.length] = CRT_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION;


var PED_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION = {
								type:"PED", 
								filial:{
									property:"filialByIdFilialOrigem", 
									idProperty:"idFilial", 
									criteriaProperty:"sgFilial", 
									service:"lms.municipios.filialService.findLookup", 
									actionServiceMethod:"findLookupFilialByDocumentoServico",
									url:"/municipios/manterFiliais.do",
									propertyMappings:[
										{ 
						 					modelProperty:"sgFilial", 
											criteriaProperty:"filialByIdFilialOrigem.sgFilial", 
											inlineQuery:true
										}, 
										{ 
						 					modelProperty:"empresa.tpEmpresa", 
											criteriaProperty:"empresa.tpEmpresa", 
											inlineQuery:true
										}, 
										{
											modelProperty:"sgFilial", 
											relatedProperty:"filialByIdFilialOrigem.sgFilial"
										},
										{ 
											modelProperty:"pessoa.nmFantasia", 
											relatedProperty:"filialByIdFilialOrigem.pessoa.nmFantasia"
										}
									]
								}, 
								documentNumber:{
									property:"pedidoCompra", 
									idProperty:"idPedidoCompra", 
									criteriaProperty:"nrPedido", 
									service:"lms.expedicao.ctoInternacionalService.findLookup", 
									actionServiceMethod:"findLookupDocumentoDocumentNumberPED",
									url:"/sim/manterPedidosCompras.do", 
									maxChars:"10", 
									propertyMappings:[ 
										{
											modelProperty:"nrPedido", 
											criteriaProperty:"pedidoCompra.nrPedido",
											inlineQuery:true
										}, 
										{ 
											modelProperty:"nrPedido", 
											relatedProperty:"nrDocumento",
											disabled:false
										}, 
										{
											modelProperty:"nrPedido", 
											relatedProperty:"pedidoCompra.nrPedido"
										}								
									]
								}
							};
documentoDocumentWidgetDefinitions[documentoDocumentWidgetDefinitions.length] = PED_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION;

var PEI_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION = {
								type:"PEI", 
								filial:{
									property:"filialByIdFilialOrigem", 
									idProperty:"idFilial", 
									criteriaProperty:"sgFilial", 
									service:"lms.municipios.filialService.findLookup", 
									actionServiceMethod:"findLookupFilialByDocumentoServico",
									url:"/municipios/manterFiliais.do",
									propertyMappings:[
										{ 
						 					modelProperty:"sgFilial", 
											criteriaProperty:"filialByIdFilialOrigem.sgFilial", 
											inlineQuery:true
										}, 
										{ 
						 					modelProperty:"empresa.tpEmpresa", 
											criteriaProperty:"empresa.tpEmpresa", 
											inlineQuery:true
										}, 
										{
											modelProperty:"sgFilial", 
											relatedProperty:"filialByIdFilialOrigem.sgFilial"
										},
										{ 
											modelProperty:"pessoa.nmFantasia", 
											relatedProperty:"filialByIdFilialOrigem.pessoa.nmFantasia"
										}
									]
								}, 
								documentNumber:{
									property:"pedidoCompra", 
									idProperty:"idPedidoCompra", 
									criteriaProperty:"nrPedidoInternacional", 
									service:"lms.expedicao.ctoInternacionalService.findLookup", 
									actionServiceMethod:"findLookupDocumentoDocumentNumberPEI",
									url:"/sim/manterPedidosCompras.do", 
									maxChars:"10",
									propertyMappings:[
										{
											modelProperty:"nrPedidoInternacional", 
											criteriaProperty:"pedidoCompra.nrPedidoInternacional", 
											inlineQuery:true
										}, 
										{
											modelProperty:"nrPedidoInternacional", 
											relatedProperty:"nrDocumento",
											disabled:false
										},  
										{
											modelProperty:"nrPedidoInternacional", 
											relatedProperty:"pedidoCompra.nrPedidoInternacional"
										}									
									]
								}
							};
documentoDocumentWidgetDefinitions[documentoDocumentWidgetDefinitions.length] = PEI_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION;


var MAE_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION = {
								type:"MAE", 
								filial:{
									property:"filialByIdFilialOrigem", 
									idProperty:"idFilial", 
									criteriaProperty:"sgFilial", 
									service:"lms.municipios.filialService.findLookup",
									actionServiceMethod:"findLookupFilialByDocumentoServico", 
									url:"/municipios/manterFiliais.do",
									propertyMappings:[
										{ 
						 					modelProperty:"sgFilial", 
											criteriaProperty:"filialByIdFilialOrigem.sgFilial", 
											inlineQuery:true
										}, 
										{ 
						 					modelProperty:"empresa.tpEmpresa", 
											criteriaProperty:"empresa.tpEmpresa", 
											inlineQuery:true
										}, 
										{
											modelProperty:"sgFilial", 
											relatedProperty:"filialByIdFilialOrigem.sgFilial"
										},
										{ 
											modelProperty:"pessoa.nmFantasia", 
											relatedProperty:"filialByIdFilialOrigem.pessoa.nmFantasia"
										}
									]
								}, 
								documentNumber:{
									property:"manifestoEntrega", 
									idProperty:"idManifestoEntrega", 
									criteriaProperty:"nrManifestoEntrega", 
									service:"lms.entrega.manifestoEntregaService.findLookup", 
									actionServiceMethod:"findLookupDocumentoDocumentNumberMAE", 
									url:"/entrega/consultarManifestosEntregaLookup.do", 
									maxChars:"8", 
									mask:"00000000",
									propertyMappings:[
										{ 
											modelProperty:"nrManifestoEntrega", 
											criteriaProperty:"manifestoEntrega.nrManifestoEntrega", 
											inlineQuery:true
										}, 
										{
											modelProperty:"nrManifestoEntrega", 
											relatedProperty:"nrDocumento",
											disabled:false
										},
										{
											modelProperty:"nrManifestoEntrega", 
											relatedProperty:"manifestoEntrega.nrManifestoEntrega"
										},
										{ 
											modelProperty:"filial.idFilial", 
											criteriaProperty:"filialByIdFilialOrigem.idFilial", 
											inlineQuery:true
										},
										{ 
											modelProperty:"filial.sgFilial", 
											criteriaProperty:"filialByIdFilialOrigem.sgFilial",
											inlineQuery:false
										},
										{ 
											modelProperty:"filial.pessoa.nmFantasia", 
											criteriaProperty:"filialByIdFilialOrigem.pessoa.nmFantasia",
											inlineQuery:false
										},										
										{ 
											modelProperty:"filial.sgFilial", 
											relatedProperty:"filialByIdFilialOrigem.sgFilial",
											blankFill:false											
										},
										{ 
											modelProperty:"filial.idFilial", 
											relatedProperty:"filialByIdFilialOrigem.idFilial",
											blankFill:false											
										},
										{ 
											modelProperty:"filial.pessoa.nmFantasia", 
											relatedProperty:"filialByIdFilialOrigem.pessoa.nmFantasia",
											blankFill:false											
										}
									]
								}
							};
documentoDocumentWidgetDefinitions[documentoDocumentWidgetDefinitions.length] = MAE_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION;

var MAV_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION = {
								type:"MAV", 
								filial:{
									property:"filialByIdFilialOrigem", 
									idProperty:"idFilial", 
									criteriaProperty:"sgFilial", 
									service:"lms.municipios.filialService.findLookup", 
									actionServiceMethod:"findLookupFilialByDocumentoServico", 
									url:"/municipios/manterFiliais.do",
									propertyMappings:[
										{ 
						 					modelProperty:"sgFilial", 
											criteriaProperty:"filialByIdFilialOrigem.sgFilial", 
											inlineQuery:true
										}, 
										{ 
						 					modelProperty:"empresa.tpEmpresa", 
											criteriaProperty:"empresa.tpEmpresa", 
											inlineQuery:true
										}, 
										{
											modelProperty:"sgFilial", 
											relatedProperty:"filialByIdFilialOrigem.sgFilial"
										},
										{ 
											modelProperty:"pessoa.nmFantasia", 
											relatedProperty:"filialByIdFilialOrigem.pessoa.nmFantasia"
										}
									]
								}, 
								documentNumber:{
									property:"manifestoViagemNacional", 
									idProperty:"idManifestoViagemNacional", 
									criteriaProperty:"nrManifestoOrigem", 
									service:"lms.expedicao.manifestoViagemNacionalService.findLookup", 
									actionServiceMethod:"findLookupDocumentoDocumentNumberMAV", 
									url:"/expedicao/manterManifestosViagem.do", 
									maxChars:"6", 
									mask:"000000",
									propertyMappings:[
										{ 
											modelProperty:"nrManifestoOrigem", 
											criteriaProperty:"manifestoViagemNacional.nrManifestoOrigem", 
											inlineQuery:true,
											copyPopup:false
										}, 
										{ 
											modelProperty:"nrManifesto", 
											criteriaProperty:"manifestoViagemNacional.nrManifestoOrigem", 
											inlineQuery:false, 
											disable:false
										}, 
										{
											modelProperty:"nrManifestoOrigem", 
											relatedProperty:"nrDocumento",
											disabled:false
										},
										{
											modelProperty:"nrManifestoOrigem", 
											relatedProperty:"manifestoViagemNacional.nrManifestoOrigem"
										},
										{
											modelProperty:"manifesto.filialByIdFilialOrigem.idFilial", 
											relatedProperty:"filialByIdFilialOrigem.idFilial"
										},
										{
											modelProperty:"manifesto.filialByIdFilialOrigem.sgFilial", 
											relatedProperty:"filialByIdFilialOrigem.sgFilial"
										},
										{ 
											modelProperty:"manifesto.filialByIdFilialOrigem.pessoa.nmFantasia", 
											relatedProperty:"filialByIdFilialOrigem.pessoa.nmFantasia"
										},
										{ 
											modelProperty:"filialOrigem.idFilial", 
											criteriaProperty:"filialByIdFilialOrigem.idFilial", 
											inlineQuery:false
										},
										{ 
											modelProperty:"manifesto.filialByIdFilialOrigem.idFilial", 
											criteriaProperty:"filialByIdFilialOrigem.idFilial", 
											inlineQuery:true,
											copyPopup:false
										},
										{ 
											modelProperty:"filial.nmFantasiaOrigem", 
											criteriaProperty:"filialByIdFilialOrigem.pessoa.nmFantasia", 
											inlineQuery:false
										},
										{ 
											modelProperty:"filialOrigem.sgFilial", 
											criteriaProperty:"filialByIdFilialOrigem.sgFilial", 
											inlineQuery:false
										}
									]
								}
							};
documentoDocumentWidgetDefinitions[documentoDocumentWidgetDefinitions.length] = MAV_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION;

var MDA_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION = {
								type:"MDA", 
								filial:{
									property:"filialByIdFilialOrigem", 
									idProperty:"idFilial", 
									criteriaProperty:"sgFilial", 
									service:"lms.municipios.filialService.findLookup", 
									actionServiceMethod:"findLookupFilialByDocumentoServico",
									url:"/municipios/manterFiliais.do",
									propertyMappings:[
										{ 
						 					modelProperty:"sgFilial", 
											criteriaProperty:"filialByIdFilialOrigem.sgFilial", 
											inlineQuery:true
										}, 
										{ 
						 					modelProperty:"empresa.tpEmpresa", 
											criteriaProperty:"empresa.tpEmpresa", 
											inlineQuery:true
										}, 
										{
											modelProperty:"sgFilial", 
											relatedProperty:"filialByIdFilialOrigem.sgFilial"
										},
										{ 
											modelProperty:"pessoa.nmFantasia", 
											relatedProperty:"filialByIdFilialOrigem.pessoa.nmFantasia"
										}
									]
								}, 
								documentNumber:{
									property:"mda", 
									idProperty:"idDoctoServico", 
									criteriaProperty:"nrMda", 
									service:"lms.pendencia.mdaService.findLookup", 
									actionServiceMethod:"findLookupDocumentoDocumentNumberMDA",
									url:"/pendencia/consultarMDA.do", 
									maxChars:"8", 
									mask:"00000000",
									propertyMappings:[
										{ 
											modelProperty:"nrDoctoServico", 
											criteriaProperty:"mda.nrMda", 
											inlineQuery:true,
											disable:false
										}, 
										{
											modelProperty:"nrDoctoServico", 
											relatedProperty:"nrDocumento",
											disabled:false
										},
										{
											modelProperty:"nrDoctoServico", 
											relatedProperty:"mda.nrMda"
										},										
										{ 
											modelProperty:"filialByIdFilialOrigem.idFilial", 
											criteriaProperty:"filialByIdFilialOrigem.idFilial",
											inlineQuery:true,
											disable:false
										},
										{ 
											modelProperty:"filialByIdFilialOrigem.sgFilial", 
											criteriaProperty:"filialByIdFilialOrigem.sgFilial",
											inlineQuery:false,
											disable:false
										},										
										{ 
											modelProperty:"filialByIdFilialOrigem.sgFilial", 
											relatedProperty:"filialByIdFilialOrigem.sgFilial",
											blankFill:false											
										},
										{ 
											modelProperty:"filialByIdFilialOrigem.idFilial", 
											relatedProperty:"filialByIdFilialOrigem.idFilial",
											blankFill:false											
										},
										{ 
											modelProperty:"filialByIdFilialOrigem.pessoa.nmFantasia", 
											relatedProperty:"filialByIdFilialOrigem.pessoa.nmFantasia",
											blankFill:false											
										}
									]
								}
							};
documentoDocumentWidgetDefinitions[documentoDocumentWidgetDefinitions.length] = MDA_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION;

var MIC_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION = {
								type:"MIC", 
								filial:{
									property:"filialByIdFilialOrigem", 
									idProperty:"idFilial", 
									criteriaProperty:"sgFilial", 
									service:"lms.municipios.filialService.findLookup", 
									actionServiceMethod:"findLookupFilialByDocumentoServico",
									url:"/municipios/manterFiliais.do"
								}, 
								documentNumber:{
									property:"manifestoInternacional", 
									idProperty:"idManifestoInternacional", 
									criteriaProperty:"nrManifestoInt",
									service:"lms.pendencia.mdaService.findLookup", 
									actionServiceMethod:"findLookupDocumentoDocumentNumberMIC",
									url:"", 
									maxChars:"6", 
									mask:"000000",
									propertyMappings:[
										{ 
											modelProperty:"nrManifestoInt", 
											criteriaProperty:"manifestoInternacional.nrManifestoInt", 
											inlineQuery:true
										}, 
										{
											modelProperty:"nrManifestoInt", 
											relatedProperty:"nrDocumento",
											disabled:false
										},
										{
											modelProperty:"nrManifestoInt", 
											relatedProperty:"manifestoInternacional.nrManifestoInt"
										},
										{
											modelProperty:"tpMic", 
											criteriaProperty:"tpMic_mic",
											inlineQuery:true
										},
										{ 
											modelProperty:"filial.idFilial", 
											criteriaProperty:"filialByIdFilialOrigem.idFilial",
											inlineQuery:true
										}
									]
								}
							};
documentoDocumentWidgetDefinitions[documentoDocumentWidgetDefinitions.length] = MIC_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION;

var MID_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION = {
								type:"MID", 
								filial:{
									property:"filialByIdFilialOrigem", 
									idProperty:"idFilial", 
									criteriaProperty:"sgFilial", 
									service:"lms.municipios.filialService.findLookup", 
									actionServiceMethod:"findLookupFilialByDocumentoServico",
									url:"/municipios/manterFiliais.do"
								}, 
								documentNumber:{
									property:"manifestoInternacional", 
									idProperty:"idManifestoInternacional", 
									criteriaProperty:"nrManifestoInt",
									service:"lms.pendencia.mdaService.findLookup", 
									actionServiceMethod:"findLookupDocumentoDocumentNumberMID",
									url:"", 
									maxChars:"6", 
									mask:"000000",
									propertyMappings:[
										{ 
											modelProperty:"nrManifestoInt", 
											criteriaProperty:"manifestoInternacional.nrManifestoInt", 
											inlineQuery:true
										}, 
										{
											modelProperty:"nrManifestoInt", 
											relatedProperty:"nrDocumento",
											disabled:false
										},
										{
											modelProperty:"nrManifestoInt", 
											relatedProperty:"manifestoInternacional.nrManifestoInt"
										},
										{
											modelProperty:"tpMic", 
											criteriaProperty:"tpMic_mid",
											inlineQuery:true
										},
										{ 
											modelProperty:"filial.idFilial", 
											criteriaProperty:"filialByIdFilialOrigem.idFilial",
											inlineQuery:true
										}
									]
								}
							};
documentoDocumentWidgetDefinitions[documentoDocumentWidgetDefinitions.length] = MID_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION;


var NFT_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION = {
								type:"NFT", 
								filial:{
									property:"filialByIdFilialOrigem", 
									idProperty:"idFilial", 
									criteriaProperty:"sgFilial", 
									service:"lms.municipios.filialService.findLookup", 
									actionServiceMethod:"findLookupFilialByDocumentoServico",
									url:"/municipios/manterFiliais.do",
									propertyMappings:[
										{ 
						 					modelProperty:"sgFilial", 
											criteriaProperty:"filialByIdFilialOrigem.sgFilial", 
											inlineQuery:true
										}, 
										{ 
						 					modelProperty:"empresa.tpEmpresa", 
											criteriaProperty:"empresa.tpEmpresa", 
											inlineQuery:true
										}, 
										{
											modelProperty:"sgFilial", 
											relatedProperty:"filialByIdFilialOrigem.sgFilial"
										},
										{ 
											modelProperty:"pessoa.nmFantasia", 
											relatedProperty:"filialByIdFilialOrigem.pessoa.nmFantasia"
										}
									]
								}, 
								documentNumber:{
									property:"notaFiscalServico", 
									idProperty:"idDoctoServico", 
									criteriaProperty:"nrNotaFiscalServico", 
									service:"lms.expedicao.notaFiscalServicoService.findLookup", 
									actionServiceMethod:"findLookupServiceDocumentNumberNFT",
									url:"/expedicao/pesquisarConhecimento.do", 
									maxChars:"8", 
									mask:"00000000", 
									propertyMappings:[
										{ 
											modelProperty:"nrConhecimento", 
											criteriaProperty:"conhecimento.nrConhecimento",
											inlineQuery:true
										},
										{ 
											modelProperty:"tpDocumentoServico", 
											criteriaProperty:"tpDocumentoServico",
											inlineQuery:true
										},
										{ 
											modelProperty:"nrConhecimento", 
											relatedProperty:"nrDocumento",
											disabled:false
										},
										{ 
											modelProperty:"nrConhecimento", 
											relatedProperty:"conhecimento.nrConhecimento"
										},										
										{ 
											modelProperty:"filialByIdFilialOrigem.idFilial", 
											criteriaProperty:"filialByIdFilialOrigem.idFilial",
											inlineQuery:true
										},
										{ 
											modelProperty:"filialByIdFilialOrigem.sgFilial", 
											criteriaProperty:"filialByIdFilialOrigem.sgFilial",
											inlineQuery:false
										},
										{ 
											modelProperty:"filialByIdFilialOrigem.pessoa.nmFantasia", 
											criteriaProperty:"filialByIdFilialOrigem.pessoa.nmFantasia",
											inlineQuery:false
										},										
										{ 
											modelProperty:"filialByIdFilialOrigem.sgFilial", 
											relatedProperty:"filialByIdFilialOrigem.sgFilial",
											blankFill:false											
										},
										{ 
											modelProperty:"filialByIdFilialOrigem.idFilial", 
											relatedProperty:"filialByIdFilialOrigem.idFilial",
											blankFill:false											
										},
										{ 
											modelProperty:"filialByIdFilialOrigem.pessoa.nmFantasia", 
											relatedProperty:"filialByIdFilialOrigem.pessoa.nmFantasia",
											blankFill:false											
										}
									]
								}
							};
documentoDocumentWidgetDefinitions[documentoDocumentWidgetDefinitions.length] = NFT_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION;

var RRE_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION = {
								type:"RRE", 		
								filial:{
									property:"filialByIdFilialOrigem", 
									idProperty:"idFilial", 
									criteriaProperty:"sgFilial", 
									service:"lms.municipios.filialService.findLookup", 
									actionServiceMethod:"findLookupFilialByDocumentoServico",
									url:"/municipios/manterFiliais.do",
									propertyMappings:[
										{ 
						 					modelProperty:"sgFilial", 
											criteriaProperty:"filialByIdFilialOrigem.sgFilial", 
											inlineQuery:true
										}, 
										{ 
						 					modelProperty:"empresa.tpEmpresa", 
											criteriaProperty:"empresa.tpEmpresa", 
											inlineQuery:true
										}, 
										{
											modelProperty:"sgFilial", 
											relatedProperty:"filialByIdFilialOrigem.sgFilial"
										},
										{ 
											modelProperty:"pessoa.nmFantasia", 
											relatedProperty:"filialByIdFilialOrigem.pessoa.nmFantasia"
										}
									]
								}, 						
								documentNumber:{
									property:"reciboReembolso", 
									idProperty:"idDoctoServico", 
									criteriaProperty:"nrReciboReembolso", 
									service:"lms.entrega.reciboReembolsoService.findLookup", 
									actionServiceMethod:"findLookupDocumentoDocumentNumberRRE",
									url:"/entrega/manterReembolsos.do", 
									maxChars:"8", 
									mask:"00000000", 
									propertyMappings:[
										{
											modelProperty:"nrReciboReembolso", 
											criteriaProperty:"reciboReembolso.nrReciboReembolso", 
											inlineQuery:true
										}, 
										{
											modelProperty:"nrReciboReembolso", 
											relatedProperty:"nrDocumento",
											disabled:false
										},
										{
											modelProperty:"nrReciboReembolso", 
											relatedProperty:"reciboReembolso.nrReciboReembolso"
										},
										{ 
											modelProperty:"filialByIdFilialOrigem.idFilial", 
											criteriaProperty:"filialByIdFilialOrigem.idFilial",
											inlineQuery:true
										},
										{ 
											modelProperty:"filialByIdFilialOrigem.sgFilial", 
											criteriaProperty:"filialByIdFilialOrigem.sgFilial",
											inlineQuery:false
										},
										{ 
											modelProperty:"filialByIdFilialOrigem.pessoa.nmFantasia", 
											criteriaProperty:"filialByIdFilialOrigem.pessoa.nmFantasia",
											inlineQuery:false
										},										
										{ 
											modelProperty:"filialByIdFilialOrigem.sgFilial", 
											relatedProperty:"filialByIdFilialOrigem.sgFilial",
											blankFill:false											
										},
										{ 
											modelProperty:"filialByIdFilialOrigem.idFilial", 
											relatedProperty:"filialByIdFilialOrigem.idFilial",
											blankFill:false											
										},
										{ 
											modelProperty:"filialByIdFilialOrigem.pessoa.nmFantasia", 
											relatedProperty:"filialByIdFilialOrigem.pessoa.nmFantasia",
											blankFill:false
										}
									]
								}
							};
documentoDocumentWidgetDefinitions[documentoDocumentWidgetDefinitions.length] = RRE_DOCUMENTO_DOCUMENT_WIDGET_DEFINITION;

