var manifestoDocumentWidgetDefinitions = new Array();

var EN_MANIFESTO_DOCUMENT_WIDGET_DEFINITION = {
								type:"EN", 
								filial:{
									property:"manifesto.filialByIdFilialOrigem", 
									idProperty:"idFilial", 
									criteriaProperty:"sgFilial", 
									service:"lms.municipios.filialService.findLookup",
									actionServiceMethod:"findLookupManifestoDocumentFilialEN", 
									url:"/municipios/manterFiliais.do",
									propertyMappings:[
										{ 
						 					modelProperty:"sgFilial", 
											criteriaProperty:"manifesto.filialByIdFilialOrigem.sgFilial", 
											inlineQuery:true
										}, 
										{
											modelProperty:"sgFilial", 
											relatedProperty:"manifesto.filialByIdFilialOrigem.sgFilial"
										},
										{ 
											modelProperty:"pessoa.nmFantasia", 
											relatedProperty:"manifesto.filialByIdFilialOrigem.pessoa.nmFantasia"
										}
									]
								}, 
								documentNumber:{
									property:"manifesto.manifestoEntrega", 
									idProperty:"idManifestoEntrega", 
									criteriaProperty:"nrManifestoEntrega", 
									service:"lms.entrega.manifestoEntregaService.findLookup", 
									actionServiceMethod:"findLookupManifestoDocumentNumberEN", 
									url:"/entrega/consultarManifestosEntrega.do", 
									maxChars:"8", 
									mask:"00000000",
									propertyMappings:[
										{ 
											modelProperty:"nrManifestoEntrega", 
											criteriaProperty:"manifesto.manifestoEntrega.nrManifestoEntrega", 
											inlineQuery:true,
											copyPopup:false
										}, 
										{ 
											modelProperty:"nrManifestoEntrega", 
											criteriaProperty:"manifesto.manifestoEntrega.nrManifestoEntrega", 
											inlineQuery:false, 
											disable:false
										}, 
										{
											modelProperty:"nrManifestoEntrega", 
											relatedProperty:"manifesto.manifestoEntrega.nrManifestoEntrega",
											disabled:false
										},
										
										
										{ 
											modelProperty:"filial.idFilial", 
											criteriaProperty:"manifesto.filialByIdFilialOrigem.idFilial", 
											inlineQuery:false 
										},
										{ 
											modelProperty:"filial.idFilial", 
											criteriaProperty:"manifesto.filialByIdFilialOrigem.idFilial", 
											inlineQuery:true,
											copyPopup:false
										},
										{
											modelProperty:"idFilialManifesto", 
											relatedProperty:"manifesto.filialByIdFilialOrigem.idFilial",
											blankFill:false											
										},
										
										
										{ 
											modelProperty:"filial.sgFilial", 
											criteriaProperty:"manifesto.filialByIdFilialOrigem.sgFilial", 
											inlineQuery:false, 
											disable:false
										},
										{ 
											modelProperty:"filial.sgFilial", 
											criteriaProperty:"manifesto.filialByIdFilialOrigem.sgFilial", 
											inlineQuery:true,
											copyPopup:false
										},
										{
											modelProperty:"sgFilialManifesto", 
											relatedProperty:"manifesto.filialByIdFilialOrigem.sgFilial",
											blankFill:false											
										},
										
										{ 
											modelProperty:"filial.pessoa.nmFantasia", 
											criteriaProperty:"manifesto.filialByIdFilialOrigem.pessoa.nmFantasia", 
											inlineQuery:false,
											disable:false
										},
										{
											modelProperty:"nmFantasiaFilialManifesto", 
											relatedProperty:"manifesto.filialByIdFilialOrigem.pessoa.nmFantasia",
											blankFill:false
										},
										
										{ 
											modelProperty:"tpSituacaoManifesto", 
											criteriaProperty:"manifesto.tpStatusManifestoEntrega", 
											inlineQuery:false, 
											disable:false
										},
										{ 
											modelProperty:"tpSituacaoManifesto", 
											criteriaProperty:"manifesto.tpStatusManifestoEntrega", 
											inlineQuery:true,
											copyPopup:false
										},
										
										
										{ 
											modelProperty:"tpManifestoEntrega", 
											criteriaProperty:"manifesto.tpManifestoEntrega", 
											inlineQuery:false, 
											disable:true
										},
										{ 
											modelProperty:"tpManifestoEntrega", 
											criteriaProperty:"manifesto.tpManifestoEntrega", 
											inlineQuery:true,
											copyPopup:false
										}
									]
								}
							};
manifestoDocumentWidgetDefinitions[manifestoDocumentWidgetDefinitions.length] = EN_MANIFESTO_DOCUMENT_WIDGET_DEFINITION;

var VN_MANIFESTO_DOCUMENT_WIDGET_DEFINITION = {
								type:"VN", 
								filial:{
									property:"manifesto.filialByIdFilialOrigem", 
									idProperty:"idFilial", 
									criteriaProperty:"sgFilial", 
									service:"lms.municipios.filialService.findLookup", 
									actionServiceMethod:"findLookupManifestoDocumentFilialVN", 
									url:"/municipios/manterFiliais.do",
									propertyMappings:[
										{ 
						 					modelProperty:"sgFilial", 
											criteriaProperty:"manifesto.filialByIdFilialOrigem.sgFilial", 
											inlineQuery:true
										}, 
										{
											modelProperty:"sgFilial", 
											relatedProperty:"manifesto.filialByIdFilialOrigem.sgFilial"
										},
										{ 
											modelProperty:"pessoa.nmFantasia", 
											relatedProperty:"manifesto.filialByIdFilialOrigem.pessoa.nmFantasia"
										}
									]
								}, 
								documentNumber:{
									property:"manifesto.manifestoViagemNacional", 
									idProperty:"idManifestoViagemNacional", 
									criteriaProperty:"nrManifestoOrigem", 
									service:"lms.expedicao.manifestoViagemNacionalService.findLookup", 
									actionServiceMethod:"findLookupManifestoDocumentNumberVN", 
									url:"/expedicao/manterManifestosViagem.do", 
									maxChars:"6", 
									mask:"000000",
									propertyMappings:[
										{ 
											modelProperty:"nrManifestoOrigem", 
											criteriaProperty:"manifesto.manifestoViagemNacional.nrManifestoOrigem", 
											inlineQuery:true,
											copyPopup:false
										}, 
										{  
											modelProperty:"nrManifesto", 
											criteriaProperty:"manifesto.manifestoViagemNacional.nrManifestoOrigem", 
											inlineQuery:false, 
											disable:false
										}, 
										{
											modelProperty:"nrManifestoOrigem", 
											relatedProperty:"manifesto.manifestoViagemNacional.nrManifestoOrigem",
											disabled:false
										},
										{
											modelProperty:"manifesto.filialByIdFilialOrigem.idFilial", 
											relatedProperty:"manifesto.filialByIdFilialOrigem.idFilial",
											blankFill:false
										},
										{
											modelProperty:"manifesto.filialByIdFilialOrigem.sgFilial", 
											relatedProperty:"manifesto.filialByIdFilialOrigem.sgFilial",
											blankFill:false											
										},
										{ 
											modelProperty:"manifesto.filialByIdFilialOrigem.pessoa.nmFantasia", 
											relatedProperty:"manifesto.filialByIdFilialOrigem.pessoa.nmFantasia",
											blankFill:false											
										},
										{ 
											modelProperty:"filialOrigem.idFilial", 
											criteriaProperty:"manifesto.filialByIdFilialOrigem.idFilial", 
											inlineQuery:false 
										},
										{ 
											modelProperty:"manifesto.filialByIdFilialOrigem.idFilial", 
											criteriaProperty:"manifesto.filialByIdFilialOrigem.idFilial", 
											inlineQuery:true,
											copyPopup:false
										},
										{ 
											modelProperty:"filialOrigem.sgFilial", 
											criteriaProperty:"manifesto.filialByIdFilialOrigem.sgFilial", 
											inlineQuery:false
										},
										{ 
											modelProperty:"filial.nmFantasiaOrigem", 
											criteriaProperty:"manifesto.filialByIdFilialOrigem.pessoa.nmFantasia", 
											inlineQuery:false
										}
									]
								} 
							};
manifestoDocumentWidgetDefinitions[manifestoDocumentWidgetDefinitions.length] = VN_MANIFESTO_DOCUMENT_WIDGET_DEFINITION;

var VI_MANIFESTO_DOCUMENT_WIDGET_DEFINITION = {
								type:"VI", 
								filial:{
									property:"manifesto.filialByIdFilialOrigem", 
									idProperty:"idFilial", 
									criteriaProperty:"sgFilial", 
									service:"lms.municipios.filialService.findLookup", 
									actionServiceMethod:"findLookupManifestoDocumentFilialVI", 
									url:"/municipios/manterFiliais.do",
									propertyMappings:[
										{ 
						 					modelProperty:"sgFilial", 
											criteriaProperty:"manifesto.filialByIdFilialOrigem.sgFilial", 
											inlineQuery:true
										}, 
										{
											modelProperty:"sgFilial", 
											relatedProperty:"manifesto.filialByIdFilialOrigem.sgFilial"
										},
										{ 
											modelProperty:"pessoa.nmFantasia", 
											relatedProperty:"manifesto.filialByIdFilialOrigem.pessoa.nmFantasia"
										}
									]
								}, 
								documentNumber:{
									property:"manifesto.manifestoInternacional", 
									idProperty:"idManifestoInternacional", 
									criteriaProperty:"nrManifestoInt", 
									service:"lms.expedicao.manifestoInternacionalService.findLookup", 
									actionServiceMethod:"findLookupManifestoDocumentNumberVI", 
									url:"/expedicao/manterManifestosViagem.do", 
									maxChars:"6",
									mask:"000000",
									propertyMappings:[
										{ 
											modelProperty:"nrManifestoInt", 
											criteriaProperty:"manifesto.manifestoInternacional.nrManifestoInt", 
											inlineQuery:true,
											copyPopup:false
										}, 
										{ 
											modelProperty:"nrManifestoInt", 
											criteriaProperty:"manifesto.manifestoInternacional.nrManifestoInt", 
											inlineQuery:false, 
											disable:false
										}, 
										{
											modelProperty:"nrManifestoInt", 
											relatedProperty:"manifesto.manifestoInternacional.nrManifestoInt",
											disabled:false
										},
										{ 
											modelProperty:"manifesto.filialByIdFilialOrigem.idFilial", 
											criteriaProperty:"manifesto.filialByIdFilialOrigem.idFilial", 
											inlineQuery:false, 
											disable:false
										},
										{ 
											modelProperty:"manifesto.filialByIdFilialOrigem.idFilial", 
											criteriaProperty:"manifesto.filialByIdFilialOrigem.idFilial", 
											inlineQuery:true,
											copyPopup:false
										},
										{ 
											modelProperty:"manifesto.filialByIdFilialOrigem.sgFilial", 
											criteriaProperty:"manifesto.filialByIdFilialOrigem.sgFilial", 
											inlineQuery:false, 
											disable:false
										}, 
										{ 
											modelProperty:"manifesto.filialByIdFilialOrigem.sgFilial", 
											criteriaProperty:"manifesto.filialByIdFilialOrigem.sgFilial", 
											inlineQuery:true,
											copyPopup:false
										}
									]
								}
							};
manifestoDocumentWidgetDefinitions[manifestoDocumentWidgetDefinitions.length] = VI_MANIFESTO_DOCUMENT_WIDGET_DEFINITION;

var CO_MANIFESTO_DOCUMENT_WIDGET_DEFINITION = {
								type:"CO", 
								filial:{
									property:"manifestoColeta.filial", 
									idProperty:"idFilial", 
									criteriaProperty:"sgFilial", 
									service:"lms.municipios.filialService.findLookup", 
									actionServiceMethod:"findLookupManifestoDocumentFilialCO", 
									url:"/municipios/manterFiliais.do",
									propertyMappings:[
										{ 
						 					modelProperty:"sgFilial", 
											criteriaProperty:"manifesto.filialByIdFilialOrigem.sgFilial", 
											inlineQuery:true
										}, 
										{
											modelProperty:"sgFilial", 
											relatedProperty:"manifesto.filialByIdFilialOrigem.sgFilial"
										},
										{ 
											modelProperty:"pessoa.nmFantasia", 
											relatedProperty:"manifesto.filialByIdFilialOrigem.pessoa.nmFantasia"
										}
									]
								},
								documentNumber:{
									property:"manifestoColeta", 
									idProperty:"idManifestoColeta", 
									criteriaProperty:"nrManifesto", 
									service:"lms.coleta.manifestoColetaService.findLookup", 
									actionServiceMethod:"findLookupManifestoDocumentNumberCO", 
									url:"/coleta/manterManifestosColetaPopUp.do", 
									maxChars:"6",
									mask:"000000",
									propertyMappings:[
										{ 
											modelProperty:"nrManifesto", 
											criteriaProperty:"manifestoColeta.nrManifesto", 
											inlineQuery:true
										}, 
										{ 
											modelProperty:"filial.idFilial", 
											criteriaProperty:"manifesto.filialByIdFilialOrigem.idFilial", 
											inlineQuery:true
										},
										{ 
											modelProperty:"filial.sgFilial", 
											criteriaProperty:"manifesto.filialByIdFilialOrigem.sgFilial", 
											inlineQuery:true
										},
										{ 
											modelProperty:"filial.pessoa.nmFantasia", 
											criteriaProperty:"manifesto.filialByIdFilialOrigem.pessoa.nmFantasia", 
											inlineQuery:false
										},
										{
											modelProperty:"nrManifesto", 
											relatedProperty:"manifestoColeta.nrManifesto",
											disabled:false
										},
										{
											modelProperty:"filial.idFilial", 
											relatedProperty:"manifesto.filialByIdFilialOrigem.idFilial",
											blankFill:false
										},
										{
											modelProperty:"filial.sgFilial", 
											relatedProperty:"manifesto.filialByIdFilialOrigem.sgFilial",
											blankFill:false											
										},
										{ 
											modelProperty:"filial.pessoa.nmFantasia", 
											relatedProperty:"manifesto.filialByIdFilialOrigem.pessoa.nmFantasia",
											blankFill:false											
										}
									]
								}
							};
manifestoDocumentWidgetDefinitions[manifestoDocumentWidgetDefinitions.length] = CO_MANIFESTO_DOCUMENT_WIDGET_DEFINITION;

var EP_MANIFESTO_DOCUMENT_WIDGET_DEFINITION = {
		type:"EP", 
		filial:{
			property:"manifesto.filialByIdFilialOrigem", 
			idProperty:"idFilial", 
			criteriaProperty:"sgFilial", 
			service:"lms.municipios.filialService.findLookup",
			actionServiceMethod:"findLookupManifestoDocumentFilialEP", 
			url:"/municipios/manterFiliais.do",
			propertyMappings:[
				{ 
 					modelProperty:"sgFilial", 
					criteriaProperty:"manifesto.filialByIdFilialOrigem.sgFilial", 
					inlineQuery:true
				}, 
				{
					modelProperty:"sgFilial", 
					relatedProperty:"manifesto.filialByIdFilialOrigem.sgFilial"
				},
				{ 
					modelProperty:"pessoa.nmFantasia", 
					relatedProperty:"manifesto.filialByIdFilialOrigem.pessoa.nmFantasia"
				}
			]
		}, 
		documentNumber:{
			property:"manifesto.manifestoEntrega", 
			idProperty:"idManifestoEntrega", 
			criteriaProperty:"nrManifestoEntrega", 
			service:"lms.entrega.manifestoEntregaService.findLookup", 
			actionServiceMethod:"findLookupManifestoDocumentNumberEP", 
			url:"/entrega/consultarManifestosEntrega.do", 
			maxChars:"8", 
			mask:"00000000",
			propertyMappings:[
				{ 
					modelProperty:"nrManifestoEntrega", 
					criteriaProperty:"manifesto.manifestoEntrega.nrManifestoEntrega", 
					inlineQuery:true,
					copyPopup:false
				}, 
				{ 
					modelProperty:"nrManifestoEntrega", 
					criteriaProperty:"manifesto.manifestoEntrega.nrManifestoEntrega", 
					inlineQuery:false, 
					disable:false
				}, 
				{
					modelProperty:"nrManifestoEntrega", 
					relatedProperty:"manifesto.manifestoEntrega.nrManifestoEntrega",
					disabled:false
				},
				
				
				{ 
					modelProperty:"filial.idFilial", 
					criteriaProperty:"manifesto.filialByIdFilialOrigem.idFilial", 
					inlineQuery:false 
				},
				{ 
					modelProperty:"filial.idFilial", 
					criteriaProperty:"manifesto.filialByIdFilialOrigem.idFilial", 
					inlineQuery:true,
					copyPopup:false
				},
				{
					modelProperty:"idFilialManifesto", 
					relatedProperty:"manifesto.filialByIdFilialOrigem.idFilial",
					blankFill:false											
				},
				
				
				{ 
					modelProperty:"filial.sgFilial", 
					criteriaProperty:"manifesto.filialByIdFilialOrigem.sgFilial", 
					inlineQuery:false, 
					disable:false
				},
				{ 
					modelProperty:"filial.sgFilial", 
					criteriaProperty:"manifesto.filialByIdFilialOrigem.sgFilial", 
					inlineQuery:true,
					copyPopup:false
				},
				{
					modelProperty:"sgFilialManifesto", 
					relatedProperty:"manifesto.filialByIdFilialOrigem.sgFilial",
					blankFill:false											
				},
				
				{ 
					modelProperty:"filial.pessoa.nmFantasia", 
					criteriaProperty:"manifesto.filialByIdFilialOrigem.pessoa.nmFantasia", 
					inlineQuery:false,
					disable:false
				},
				{
					modelProperty:"nmFantasiaFilialManifesto", 
					relatedProperty:"manifesto.filialByIdFilialOrigem.pessoa.nmFantasia",
					blankFill:false
				},
				
				{ 
					modelProperty:"tpSituacaoManifesto", 
					criteriaProperty:"manifesto.tpStatusManifestoEntrega", 
					inlineQuery:false, 
					disable:false
				},
				{ 
					modelProperty:"tpSituacaoManifesto", 
					criteriaProperty:"manifesto.tpStatusManifestoEntrega", 
					inlineQuery:true,
					copyPopup:false
				},
				
				
				{ 
					modelProperty:"tpManifestoEntrega", 
					criteriaProperty:"manifesto.tpManifestoEntrega", 
					inlineQuery:false, 
					disable:true
				},
				{ 
					modelProperty:"tpManifestoEntrega", 
					criteriaProperty:"manifesto.tpManifestoEntrega", 
					inlineQuery:true,
					copyPopup:false
				}
			]
		}
	};
manifestoDocumentWidgetDefinitions[manifestoDocumentWidgetDefinitions.length] = EP_MANIFESTO_DOCUMENT_WIDGET_DEFINITION;