package com.mercurio.lms.municipios.action;

import java.util.List;
import java.util.Map;

import com.mercurio.adsm.framework.report.ReportActionSupport;
import com.mercurio.adsm.framework.util.TypedFlatMap;
import com.mercurio.lms.configuracoes.model.service.ServicoService;
import com.mercurio.lms.municipios.model.Filial;
import com.mercurio.lms.municipios.model.service.FilialService;
import com.mercurio.lms.municipios.model.service.RegionalService;
import com.mercurio.lms.municipios.model.service.UnidadeFederativaService;
import com.mercurio.lms.municipios.report.EmitirFluxoCargaEntreFiliaisService;
import com.mercurio.lms.util.session.SessionUtils;

/**
 * Generated by: ADSM ActionGenerator
 *  
 * Não inserir documentação após ou remover a tag do XDoclet a seguir.
 * O valor do <code>id</code> informado abaixo deve ser utilizado para referenciar este serviço.
 * @spring.bean id="lms.municipios.emitirFluxoCargaEntreFiliaisAction"
 */

public class EmitirFluxoCargaEntreFiliaisAction extends ReportActionSupport {

   private UnidadeFederativaService unidadeFederativaService;
   private FilialService filialService;
   private ServicoService servicoService;
   private RegionalService regionalService;
	
	
	
	public void setEmitirFluxoCargaEntreFiliaisService(
			EmitirFluxoCargaEntreFiliaisService emitirFluxoCargaEntreFiliaisService) {
		this.reportServiceSupport = emitirFluxoCargaEntreFiliaisService;
	}


	public List findLookupUf(Map criteria) {
		return unidadeFederativaService.find(criteria);
	}
	public List findLookupFilial(Map criteria) {
		return filialService.findLookupFilial(criteria);
	}
	public List findComboRegional(Map criteria) {
		return regionalService.findRegional();
	}
	
	public List findComboServico(Map criteria) {
		return servicoService.find(criteria);
	}

	public TypedFlatMap findFilialUsuarioLogado() {
		Filial f = SessionUtils.getFilialSessao();
		
		TypedFlatMap m = new TypedFlatMap();
		m.put("filial.idFilial",f.getIdFilial());
		m.put("filial.sgFilial",f.getSgFilial());
		m.put("filial.pessoa.nmFantasia",f.getPessoa().getNmFantasia());
		
		return m;
	}
	
	public FilialService getFilialService() {
		return filialService;
	}



	public void setFilialService(FilialService filialService) {
		this.filialService = filialService;
	}



	public RegionalService getRegionalService() {
		return regionalService;
	}



	public void setRegionalService(RegionalService regionalService) {
		this.regionalService = regionalService;
	}



	public ServicoService getServicoService() {
		return servicoService;
	}



	public void setServicoService(ServicoService servicoService) {
		this.servicoService = servicoService;
	}



	public UnidadeFederativaService getUnidadeFederativaService() {
		return unidadeFederativaService;
	}



	public void setUnidadeFederativaService(
			UnidadeFederativaService unidadeFederativaService) {
		this.unidadeFederativaService = unidadeFederativaService;
	}
}
