package com.mercurio.lms.municipios.action;

import java.io.Serializable;
import java.util.List;
import java.util.Map;

import com.mercurio.adsm.framework.model.CrudAction;
import com.mercurio.adsm.framework.util.TypedFlatMap;
import com.mercurio.lms.municipios.model.service.CiaFilialMercurioService;

import com.mercurio.adsm.framework.annotations.ParametrizedAttribute;

/**
 * Generated by: ADSM ActionGenerator
 *  
 * Não inserir documentação após ou remover a tag do XDoclet a seguir.
 * O valor do <code>id</code> informado abaixo deve ser utilizado para referenciar este serviço.
 * @spring.bean id="lms.municipios.manterCiasAereasFiliaisAction"
 */

public class ManterCiasAereasFiliaisAction extends CrudAction {
	public void setCiaFilialMercurio(CiaFilialMercurioService ciaFilialMercurioService) {
		this.defaultService = ciaFilialMercurioService;
	}
	
	private CiaFilialMercurioService getCiaFilialMercurioService() {
		return (CiaFilialMercurioService)defaultService;
	}
	
    public void removeById(java.lang.Long id) {
        getCiaFilialMercurioService().removeById(id);
    }	

    public Serializable store(Map bean) {
    	return getCiaFilialMercurioService().storeMap(bean);
    }
    
	/**
	 *
	 */
	@ParametrizedAttribute(type = java.lang.Long.class)
    public void removeByIds(List ids) {
    	getCiaFilialMercurioService().removeByIds(ids);
    }

    public TypedFlatMap findById(java.lang.Long id) {
    	return getCiaFilialMercurioService().findByIdDetalhamento(id);
    }

}
