package com.mercurio.lms.municipios.action;

import java.io.Serializable;
import java.util.List;
import java.util.Map;

import com.mercurio.adsm.core.util.ReflectionUtils;
import com.mercurio.adsm.framework.model.CrudAction;
import com.mercurio.adsm.framework.util.TypedFlatMap;
import com.mercurio.lms.municipios.model.Filial;
import com.mercurio.lms.municipios.model.MunicipioFilialFilOrigem;
import com.mercurio.lms.municipios.model.service.FilialService;
import com.mercurio.lms.municipios.model.service.MunicipioFilialFilOrigemService;
import com.mercurio.lms.util.JTDateTimeUtils;
import com.mercurio.lms.util.JTVigenciaUtils;

import com.mercurio.adsm.framework.annotations.ParametrizedAttribute;

/**
 * Generated by: ADSM ActionGenerator
 *  
 * Não inserir documentação após ou remover a tag do XDoclet a seguir.
 * O valor do <code>id</code> informado abaixo deve ser utilizado para referenciar este serviço.
 * @spring.bean id="lms.municipios.manterFiliaisAtendidasAction"
 */

public class ManterFiliaisAtendidasAction extends CrudAction {
	private FilialService filialService;

	public Serializable store(Map bean) {
		MunicipioFilialFilOrigem municipioFilialFilOrigem = new MunicipioFilialFilOrigem();

		ReflectionUtils.copyNestedBean(municipioFilialFilOrigem,bean);

		super.store(municipioFilialFilOrigem);
		TypedFlatMap retorno = new TypedFlatMap();
		retorno.put("idMunicipioFilialFilOrigem", municipioFilialFilOrigem.getIdMunicipioFilialFilOrigem());
		retorno.put("acaoVigenciaAtual", JTVigenciaUtils.getIntegerAcaoVigencia(municipioFilialFilOrigem));

		return retorno;
	}

	public void removeById(Long id) {
		super.removeById(id);
	}

	@ParametrizedAttribute(type = Long.class)
	@Override
	public void removeByIds(List ids) {
		getMunicipioFilialFilOrigem().removeByIds(ids);
	}

	public Map findById(Long id) {
		MunicipioFilialFilOrigem m = getMunicipioFilialFilOrigem().findById(id);
		TypedFlatMap retorno = bean2map(m);
		Integer acaoVigencia = JTVigenciaUtils.getIntegerAcaoVigencia(m);
		retorno.put("acaoVigenciaAtual", acaoVigencia);

		return retorno;
	}

	private TypedFlatMap bean2map(MunicipioFilialFilOrigem bean){
		TypedFlatMap map = new TypedFlatMap();

		map.put("idMunicipioFilialFilOrigem", bean.getIdMunicipioFilialFilOrigem());
		map.put("dtVigenciaInicial", bean.getDtVigenciaInicial());
		map.put("dtVigenciaFinal", bean.getDtVigenciaFinal());

		Filial filial = bean.getFilial();
		map.put("filial.sgFilial", filial.getSgFilial());
		map.put("filial.idFilial", filial.getIdFilial());
		map.put("filial.pessoa.nmFantasia", filial.getPessoa().getNmFantasia());

		return map;		
	}

	/**
	 * Método rsponsável por buscar as filiais vigentes
	 * @param tfm
	 * @return List de filiais
	 */
	public List findLookupBySgFilialVigenteEm(TypedFlatMap tfm) {
		return filialService.findLookupBySgFilialVigenteEm(tfm.getString("sgFilial"), JTDateTimeUtils.getDataAtual(), tfm.getString("tpAcesso"));
	}

	public List findLookupFilial(TypedFlatMap tfm) {
		return filialService.findLookupBySgFilial(tfm.getString("sgFilial"), tfm.getString("tpAcesso"));
	}

	public void setMunicipioFilialFilOrigem(MunicipioFilialFilOrigemService municipioFilialFilOrigemService) {
		this.defaultService = municipioFilialFilOrigemService;
	}

	private MunicipioFilialFilOrigemService getMunicipioFilialFilOrigem() {
		return (MunicipioFilialFilOrigemService) this.defaultService;
	}
	public void setFilialService(FilialService filialService){
		this.filialService = filialService;
	}
}
