package com.mercurio.lms.municipios.action;

import java.util.List;

import com.mercurio.adsm.framework.model.CrudAction;
import com.mercurio.adsm.framework.util.TypedFlatMap;
import com.mercurio.lms.municipios.model.service.FilialServicoService;

import com.mercurio.adsm.framework.annotations.ParametrizedAttribute;

/**
 * Generated by: ADSM ActionGenerator
 *  
 * Não inserir documentação após ou remover a tag do XDoclet a seguir.
 * O valor do <code>id</code> informado abaixo deve ser utilizado para referenciar este serviço.
 * @spring.bean id="lms.municipios.manterServicosFilialAction"
 */

public class ManterServicosFilialAction extends CrudAction {
	public void setFilialServico(FilialServicoService filialServicoService) {
		this.defaultService = filialServicoService;
	}
    public void removeById(java.lang.Long id) {
        getFilialServicoService().removeById(id);
    }

	/**
	 *
	 */
	@ParametrizedAttribute(type = java.lang.Long.class)
    public void removeByIds(List ids) {
    	getFilialServicoService().removeByIds(ids);
    }

    public TypedFlatMap findById(java.lang.Long id) {
    	return getFilialServicoService().findByIdMap(id);
    }
	private FilialServicoService getFilialServicoService() {
		return ((FilialServicoService)defaultService);
	}

}
