package com.mercurio.lms.municipios.action;

import java.util.List;

import com.mercurio.adsm.framework.model.CrudAction;
import com.mercurio.lms.municipios.model.RegionalFilial;
import com.mercurio.lms.municipios.model.service.RegionalFilialService;

import com.mercurio.adsm.framework.annotations.ParametrizedAttribute;

/**
 * Generated by: ADSM ActionGenerator
 *  
 * Não inserir documentação após ou remover a tag do XDoclet a seguir.
 * O valor do <code>id</code> informado abaixo deve ser utilizado para referenciar este serviço.
 * @spring.bean id="lms.municipios.manterRegionalFilialAction"
 */

public class ManterRegionalFilialAction extends CrudAction {
	public void setRegionalFilial(RegionalFilialService regionalFilialService) {
		this.defaultService = regionalFilialService;
	}
    public void removeById(java.lang.Long id) {
        ((RegionalFilialService)defaultService).removeById(id);
    }

	/**
	 *
	 */
	@ParametrizedAttribute(type = java.lang.Long.class)
    public void removeByIds(List ids) {
    	((RegionalFilialService)defaultService).removeByIds(ids);
    }

    public RegionalFilial findById(java.lang.Long id) {
    	return ((RegionalFilialService)defaultService).findById(id);
    }

}
