package com.mercurio.lms.municipios.action;

import java.util.List;

import com.mercurio.adsm.framework.model.CrudAction;
import com.mercurio.lms.municipios.model.Zona;
import com.mercurio.lms.municipios.model.service.ZonaService;

import com.mercurio.adsm.framework.annotations.ParametrizedAttribute;

/**
 * Generated by: ADSM ActionGenerator
 *  
 * Não inserir documentação após ou remover a tag do XDoclet a seguir.
 * O valor do <code>id</code> informado abaixo deve ser utilizado para referenciar este serviço.
 * @spring.bean id="lms.municipios.manterZonasAction"
 */

public class ManterZonasAction extends CrudAction {
	public void setZona(ZonaService zonaService) {
		this.defaultService = zonaService;
	}
    public void removeById(java.lang.Long id) {
        ((ZonaService)defaultService).removeById(id);
    }

	/**
	 *
	 */
	@ParametrizedAttribute(type = java.lang.Long.class)
    public void removeByIds(List ids) {
    	((ZonaService)defaultService).removeByIds(ids);
    }

    public Zona findById(java.lang.Long id) {
    	return ((ZonaService)defaultService).findById(id);
    }

}
