package com.mercurio.lms.municipios.action;

import java.util.List;

import com.mercurio.adsm.framework.model.CrudAction;
import com.mercurio.lms.municipios.model.Feriado;
import com.mercurio.lms.municipios.model.service.FeriadoService;

import com.mercurio.adsm.framework.annotations.ParametrizedAttribute;

/**
 * Generated by: ADSM ActionGenerator
 *  
 * Não inserir documentação após ou remover a tag do XDoclet a seguir.
 * O valor do <code>id</code> informado abaixo deve ser utilizado para referenciar este serviço.
 * @spring.bean id="lms.municipios.manterFeriadosAction"
 */

public class ManterFeriadosAction extends CrudAction {
	public void setFeriado(FeriadoService feriadoService) {
		this.defaultService = feriadoService;
	}
    public void removeById(java.lang.Long id) {
        ((FeriadoService)defaultService).removeById(id);
    }

	/**
	 *
	 */
	@ParametrizedAttribute(type = java.lang.Long.class)
    public void removeByIds(List ids) {
    	((FeriadoService)defaultService).removeByIds(ids);
    }

    public Feriado findById(java.lang.Long id) {
    	return ((FeriadoService)defaultService).findById(id);
    }

}
