package com.mercurio.lms.carregamento.action;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import com.mercurio.adsm.framework.BusinessException;
import com.mercurio.adsm.framework.model.CrudAction;
import com.mercurio.adsm.framework.model.FindDefinition;
import com.mercurio.adsm.framework.model.ResultSetPage;
import com.mercurio.adsm.framework.model.service.DomainValueService;
import com.mercurio.adsm.framework.util.FilterList;
import com.mercurio.adsm.framework.util.TypedFlatMap;
import com.mercurio.lms.carregamento.model.CarregamentoDescarga;
import com.mercurio.lms.carregamento.model.Manifesto;
import com.mercurio.lms.carregamento.model.PreManifestoDocumento;
import com.mercurio.lms.carregamento.model.service.CarregamentoDescargaService;
import com.mercurio.lms.carregamento.model.service.ControleCargaService;
import com.mercurio.lms.carregamento.model.service.ManifestoService;
import com.mercurio.lms.carregamento.model.service.PreManifestoDocumentoService;
import com.mercurio.lms.entrega.model.service.ReciboReembolsoService;
import com.mercurio.lms.expedicao.model.service.ConhecimentoService;
import com.mercurio.lms.expedicao.model.service.CtoInternacionalService;
import com.mercurio.lms.expedicao.model.service.DoctoServicoService;
import com.mercurio.lms.municipios.model.Filial;
import com.mercurio.lms.municipios.model.service.FilialService;
import com.mercurio.lms.pendencia.model.service.MdaService;

import com.mercurio.adsm.framework.annotations.ParametrizedAttribute;

/**
 * Generated by: ADSM ActionGenerator
 * 
 * Não inserir documentação após ou remover a tag do XDoclet a seguir. O valor
 * do <code>id</code> informado abaixo deve ser utilizado para referenciar
 * este serviço.
 * 
 * @spring.bean id="lms.carregamento.carregarVeiculoDocumentosAction"
 */

public class CarregarVeiculoDocumentosAction extends CrudAction {
 
	private DomainValueService domainValueService;
	private FilialService filialService;
	private CarregamentoDescargaService carregamentoDescargaService;
	private ConhecimentoService conhecimentoService;
	private CtoInternacionalService ctoInternacionalService; 
	private MdaService mdaService;
	private ReciboReembolsoService reciboReembolsoService;
	private PreManifestoDocumentoService preManifestoDocumentoService;
	private DoctoServicoService doctoServicoService;
	private ManifestoService manifestoService;
	private ControleCargaService controleCargaService;
	
	public DomainValueService getDomainValueService() {
		return domainValueService;
	}

	public void setDomainValueService(DomainValueService domainValueService) {
		this.domainValueService = domainValueService;
	}

	public CarregamentoDescargaService getCarregamentoDescargaService() {
		return carregamentoDescargaService;
	}

	public void setCarregamentoDescargaService(
			CarregamentoDescargaService carregamentoDescargaService) {
		this.carregamentoDescargaService = carregamentoDescargaService;
	}

	public FilialService getFilialService() {
		return filialService;
	}

	public void setFilialService(FilialService filialService) {
		this.filialService = filialService;
	}
	
	public ConhecimentoService getConhecimentoService() {
		return conhecimentoService;
	}

	public void setConhecimentoService(ConhecimentoService conhecimentoService) {
		this.conhecimentoService = conhecimentoService;
	}

	public CtoInternacionalService getCtoInternacionalService() {
		return ctoInternacionalService;
	}

	public void setCtoInternacionalService(
			CtoInternacionalService ctoInternacionalService) {
		this.ctoInternacionalService = ctoInternacionalService;
	}

	public MdaService getMdaService() {
		return mdaService;
	}

	public void setMdaService(MdaService mdaService) {
		this.mdaService = mdaService;
	}

	public ReciboReembolsoService getReciboReembolsoService() {
		return reciboReembolsoService;
	}

	public void setReciboReembolsoService(ReciboReembolsoService reciboReembolsoService) {
		this.reciboReembolsoService = reciboReembolsoService;
	}

	public PreManifestoDocumentoService getPreManifestoDocumentoService() {
		return preManifestoDocumentoService;
	}

	public void setPreManifestoDocumentoService(
			PreManifestoDocumentoService preManifestoDocumentoService) {
		this.preManifestoDocumentoService = preManifestoDocumentoService;
	}

	public ManifestoService getManifestoService() {
		return manifestoService;
	}

	public void setManifestoService(ManifestoService manifestoService) {
		this.manifestoService = manifestoService;
	}

	public ControleCargaService getControleCargaService() {
		return controleCargaService;
	}

	public void setControleCargaService(ControleCargaService controleCargaService) {
		this.controleCargaService = controleCargaService;
	}

	/**
	 * Busca a Service default desta Action
	 * 
	 * @param carregamentoDescargaService
	 */
	public void setService(CarregamentoDescargaService carregamentoDescargaService) {
		this.defaultService = carregamentoDescargaService;
	}

	public CarregamentoDescargaService getService() {
		return (CarregamentoDescargaService) this.defaultService;
	}

	public DoctoServicoService getDoctoServicoService() {
		return doctoServicoService;
	}

	public void setDoctoServicoService(DoctoServicoService doctoServicoService) {
		this.doctoServicoService = doctoServicoService;
	}

	public CarregamentoDescarga findById(java.lang.Long id) {
		return ((CarregamentoDescargaService) defaultService).findById(id);
	}

	/**
	 * Apaga várias entidades através do Id. E para os mesmos gera um e
	 *
	 * @param ids lista com as entidades que deverão ser removida.
	 *
	 *
	 */
	@ParametrizedAttribute(type = java.lang.Long.class)
	public void removeByIds(List ids) {		
		if (!this.getPreManifestoDocumentoService().validateRemoveByIds(ids)) throw new BusinessException("LMS-05072");
		
		for (Iterator iter = ids.iterator(); iter.hasNext();) {
			Long idPreManifestoDocumento = (Long) iter.next();
			PreManifestoDocumento preManifestoDocumento = preManifestoDocumentoService.findById(idPreManifestoDocumento);
			Long idManifesto = preManifestoDocumento.getManifesto().getIdManifesto();
			Long idDoctoServico = preManifestoDocumento.getDoctoServico().getIdDoctoServico();
			this.getPreManifestoDocumentoService().generateEventoDoctoServicoByIdManifestoByIdDoctoServico(idManifesto, idDoctoServico);
		}		
		this.getPreManifestoDocumentoService().removeByIds(ids);
	}

	/**
	 * Busca a quantidade de dados da grid de carregamentos
	 */
	public Integer getRowCount(TypedFlatMap criteria) {
		
		Long idManifesto = criteria.getLong("manifesto.idManifesto");
		String tpDoctoServico = criteria.getString("doctoServico.tpDocumentoServico");
		Long idFilialDoctoServico = criteria.getLong("doctoServico.filialByIdFilialOrigem.idFilial");
		Long idDoctoServico = criteria.getLong("doctoServico.idDoctoServico");
		
		return getPreManifestoDocumentoService().getRowCountPreManifestoDoctoServicoByIdManifesto(
				idManifesto, 
				idDoctoServico, 
				tpDoctoServico, 
				idFilialDoctoServico);
	}
	
	/**
	 * Busca os registros da grid de carregamento.
	 * 
	 */
	public ResultSetPage findPaginated(TypedFlatMap criteria) {
		FindDefinition findDefinition = FindDefinition.createFindDefinition(criteria);
		Long idManifesto = criteria.getLong("manifesto.idManifesto");
		String tpDoctoServico = criteria.getString("doctoServico.tpDocumentoServico");
		Long idFilialDoctoServico = criteria.getLong("doctoServico.filialByIdFilialOrigem.idFilial");
		Long idDoctoServico = criteria.getLong("doctoServico.idDoctoServico");
		ResultSetPage rsp = getPreManifestoDocumentoService()
			.findPaginatedPreManifestosDoctoServicoByidManifesto(
					idManifesto,
					idDoctoServico,
					tpDoctoServico,
					idFilialDoctoServico,
					findDefinition);
		
		return rsp;	

	}
	
	/**
	 * Pesquisa para preencher o restante dos campos do
	 * Manifesto (inclusive campos hidden) que também servirão
	 * para a tela "adicionar documentos".
     * @param idManifesto
     * @return TypedFlatMap
	 */
	public TypedFlatMap findManifestoById(Long idManifesto){
		Manifesto manifesto = getManifestoService().findManifestoById(idManifesto);
		TypedFlatMap retorno = new TypedFlatMap();
		retorno.put("manifesto.idManifesto", manifesto.getIdManifesto());
		retorno.put("manifesto.nrPreManifesto", manifesto.getNrPreManifesto());
		retorno.put("manifesto.filialByIdFilialOrigem.sgFilial", manifesto.getFilialByIdFilialOrigem().getSgFilial());
		retorno.put("manifesto.filialByIdFilialDestino.idFilial", manifesto.getFilialByIdFilialDestino().getIdFilial());
		retorno.put("manifesto.tpModal", manifesto.getTpModal().getValue());
		return retorno; 
	}
	
	
	/**
     * Método que popula a combo de tipos de documento apenas com CTR, CRT, MDA.
     * 
     * @param criteria
     * @return List
     */
    public List findTipoDocumentoServico(Map criteria) {
        List dominiosValidos = new ArrayList();
        dominiosValidos.add("CTR");
        dominiosValidos.add("CRT");
        dominiosValidos.add("MDA");
        dominiosValidos.add("RRE");
        dominiosValidos.add("NFT");
        List retorno = getDomainValueService().findByDomainNameAndValues("DM_TIPO_DOCUMENTO_SERVICO", dominiosValidos);
        return retorno;
    }
	
	/** 
     * Busca a filial baseado no documento de serviço
     * @param criteria
     * @return
     */
    public List findLookupFilialByDocumentoServico(Map criteria) {
    	
    	FilterList filter = new FilterList(getFilialService().findLookup(criteria)) {
			public Map filterItem(Object item) {
	    			Filial filial = (Filial)item;
	    			TypedFlatMap typedFlatMap = new TypedFlatMap();
		    		typedFlatMap.put("idFilial", filial.getIdFilial());
			    	typedFlatMap.put("sgFilial", filial.getSgFilial());
				return typedFlatMap;
			}
    	};
    	
    	return (List)filter.doFilter();
    }
    
    /**
     * FindLookup para filial do tipo de DoctoServico Escolhido.
     */ 
    public List findLookupServiceDocumentFilialCTR(Map criteria) {
    	return findLookupFilialByDocumentoServico(criteria);
    }
    public List findLookupServiceDocumentFilialCRT(Map criteria) {
    	return findLookupFilialByDocumentoServico(criteria);
    }
    public List findLookupServiceDocumentFilialMDA(Map criteria) {
    	return findLookupFilialByDocumentoServico(criteria);
    }
    public List findLookupServiceDocumentFilialRRE(Map criteria) {
    	return findLookupFilialByDocumentoServico(criteria);
    }  
    public List findLookupServiceDocumentFilialNFT(Map criteria) {
    	return findLookupFilialByDocumentoServico(criteria);
    }  
    
    /**
     * FindLookup para a tag DoctoServico.
     */  
    public List findLookupServiceDocumentNumberCTR(Map criteria) {
    	return this.getConhecimentoService().findLookup(criteria);
    }
    public List findLookupServiceDocumentNumberCRT(Map criteria) {    	
    	return this.getCtoInternacionalService().findLookup(criteria);
    }    
    public List findLookupServiceDocumentNumberMDA(Map criteria) {
    	return this.getMdaService().findLookup(criteria);
    }
    public List findLookupServiceDocumentNumberRRE(Map criteria) {
    	return this.getReciboReembolsoService().findLookup(criteria);
    }
    public List findLookupServiceDocumentNumberNFT(Map criteria) {
    	return this.getConhecimentoService().findLookup(criteria);
    }
}
