package com.mercurio.lms.integracao.action;

import java.util.List;
import java.util.Map;

import com.mercurio.adsm.framework.model.CrudAction;
import com.mercurio.lms.integracao.model.service.OcorrenciaIntegracaoService;
import com.mercurio.lms.integration.pilmsc001e.CT65AA;

/**
 * Generated by: ADSM ActionGenerator
 *  
 * Não inserir documentação após ou remover a tag do XDoclet a seguir.
 * O valor do <code>id</code> informado abaixo deve ser utilizado para referenciar este serviço.
 * @spring.bean id="lms.integracao.swt.visualizarOcorrenciaIntegracaoCT65AAListAction"
 */
public class VisualizarOcorrenciaIntegracaoCT65AAListAction extends CrudAction {

	public void store(Map parameters) {
		List<CT65AA> list = (List) parameters.get("layoutList");
		Long idOcorrenciaIntegracao = (Long) parameters.get("idOcorrenciaIntegracao");
		getOcorrenciaIntegracaoService().storeLayoutCT65AAPI01e(idOcorrenciaIntegracao, list);
	}
	
	public void setOcorrenciaIntegracaoService(OcorrenciaIntegracaoService ocorrenciasIntegracaoService) {
		defaultService = ocorrenciasIntegracaoService;
	}
	
	public OcorrenciaIntegracaoService getOcorrenciaIntegracaoService() {
		return (OcorrenciaIntegracaoService) defaultService;
	}
}