package com.mercurio.lms.vendas.action;

import java.io.Serializable;
import java.util.List;

import com.mercurio.adsm.framework.model.CrudAction;
import com.mercurio.lms.vendas.model.ProcessoPce;
import com.mercurio.lms.vendas.model.service.ProcessoPceService;

import com.mercurio.adsm.framework.annotations.ParametrizedAttribute;

/**
 * Generated by: ADSM ActionGenerator
 *  
 * Não inserir documentação após ou remover a tag do XDoclet a seguir.
 * O valor do <code>id</code> informado abaixo deve ser utilizado para referenciar este serviço.
 * @spring.bean id="lms.vendas.manterProcessosAction"
 */

public class ManterProcessosAction extends CrudAction {
	
	public void setService(ProcessoPceService processoPceService) {
		this.defaultService = processoPceService;
	}
    public void removeById(java.lang.Long id) {
        ((ProcessoPceService)defaultService).removeById(id);
    }
    
    public Serializable store(ProcessoPce bean) {
        return ((ProcessoPceService)defaultService).store(bean);
    }

	/**
	 *
	 */
	@ParametrizedAttribute(type = java.lang.Long.class)
    public void removeByIds(List ids) {
    	((ProcessoPceService)defaultService).removeByIds(ids);
    }

    public ProcessoPce findById(java.lang.Long id) {
    	return ((ProcessoPceService)defaultService).findById(id);
    }
    
}
