package com.mercurio.lms.franqueados.model;

// Generated 10/04/2014 12:11:11 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.Type;
import org.joda.time.YearMonthDay;

import com.mercurio.adsm.framework.model.DomainValue;

/**
 * DistColEntFrq generated by hbm2java
 */
@Entity
@Table(name = "DIST_COL_ENT_FRQ")
@SequenceGenerator(name = "DIST_COL_ENT_FRQ_SEQ", sequenceName = "DIST_COL_ENT_FRQ_SQ", allocationSize = 1)
public class DistanciaColetaEntregaFranqueado implements java.io.Serializable {

	private long idDistColEntFrq;
	private DomainValue tpFrete;
	private DomainValue tpPavimento;
	private Integer nrKm;
	private BigDecimal pcDistancia;
	private BigDecimal vlMultiplicador;
	private YearMonthDay dtVigenciaInicial;
	private YearMonthDay dtVigenciaFinal;

	public DistanciaColetaEntregaFranqueado() {
	}

	public DistanciaColetaEntregaFranqueado(long idDistColEntFrq, DomainValue tpFrete, 
			DomainValue tpPavimento, Integer nrKm, BigDecimal pcDistancia,
			BigDecimal vlMultiplicador, YearMonthDay dtVigenciaInicial, 
			YearMonthDay dtVigenciaFinal) {
		this.idDistColEntFrq = idDistColEntFrq;
		this.tpFrete = tpFrete;
		this.tpPavimento = tpPavimento;
		this.nrKm = nrKm;
		this.pcDistancia= pcDistancia; 
		this.vlMultiplicador = vlMultiplicador;
		this.dtVigenciaInicial = dtVigenciaInicial;
		this.dtVigenciaFinal = dtVigenciaFinal;
	}

	@Id
	@Column(name = "ID_DIST_COL_ENT_FRQ", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DIST_COL_ENT_FRQ_SEQ")
	public long getIdDistColEntFrq() {
		return this.idDistColEntFrq;
	}

	public void setIdDistColEntFrq(long idDistColEntFrq) {
		this.idDistColEntFrq = idDistColEntFrq;
	}

	@Column(name = "TP_FRETE", nullable = false, length = 2)
	@Type(type = "com.mercurio.adsm.core.model.hibernate.DomainCompositeUserType", parameters = { @Parameter(name = "domainName", value = "DM_TIPO_FRETE_FRQ") })
	public DomainValue getTpFrete() {
		return this.tpFrete;
	}

	public void setTpFrete(DomainValue tpFrete) {
		this.tpFrete = tpFrete;
	}

	@Column(name = "TP_PAVIMENTO", nullable = false, length = 2)
	@Type(type = "com.mercurio.adsm.core.model.hibernate.DomainCompositeUserType", parameters = { @Parameter(name = "domainName", value = "DM_TIPO_PAVIMENTO") })
	public DomainValue getTpPavimento() {
		return this.tpPavimento;
	}

	public void setTpPavimento(DomainValue tpPavimento) {
		this.tpPavimento = tpPavimento;
	}

	@Column(name = "NR_KM", nullable = false, precision = 5, scale = 0)
	public Integer getNrKm() {
		return this.nrKm;
	}

	public void setNrKm(Integer nrKm) {
		this.nrKm = nrKm;
	}

	@Column(name = "PC_DISTANCIA", nullable = false, precision = 3, scale = 0)
	public BigDecimal getPcDistancia() {
		return this.pcDistancia;
	}

	public void setPcDistancia(BigDecimal pcDistancia) {
		this.pcDistancia = pcDistancia;
	}

	@Column(name = "VL_MULTIPLICADOR", nullable = false, precision = 5, scale = 2)
	public BigDecimal getVlMultiplicador() {
		return this.vlMultiplicador;
	}

	public void setVlMultiplicador(BigDecimal vlMultiplicador) {
		this.vlMultiplicador = vlMultiplicador;
	}

	@Column(name = "DT_VIGENCIA_INICIAL", nullable = false, length = 7)
	@Type(type = "com.mercurio.adsm.core.model.hibernate.JodaTimeYearMonthDayUserType")
	public YearMonthDay getDtVigenciaInicial() {
		return this.dtVigenciaInicial;
	}

	public void setDtVigenciaInicial(YearMonthDay dtVigenciaInicial) {
		this.dtVigenciaInicial = dtVigenciaInicial;
	}

	@Column(name = "DT_VIGENCIA_FINAL", nullable = false, length = 7)
	@Type(type = "com.mercurio.adsm.core.model.hibernate.JodaTimeYearMonthDayUserType")
	public YearMonthDay getDtVigenciaFinal() {
		return this.dtVigenciaFinal;
	}

	public void setDtVigenciaFinal(YearMonthDay dtVigenciaFinal) {
		this.dtVigenciaFinal = dtVigenciaFinal;
	}

}
