package com.mercurio.lms.franqueados.model;

// Generated 10/04/2014 12:11:11 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Type;
import org.joda.time.YearMonthDay;

/**
 * FranqueadoFranquia generated by hbm2java
 */
@Entity
@Table(name = "FRANQUEADO_FRANQUIA")
@SequenceGenerator(name = "FRANQUEADO_FRANQUIA_SEQ", sequenceName = "FRANQUEADO_FRANQUIA_SQ", allocationSize = 1)
public class FranqueadoFranquia implements java.io.Serializable{
	
	private static final long serialVersionUID = 1L;
	
	private Long idFranqueadoFranquia;
	private Franqueado franqueado;
	private Franquia franquia;
	private YearMonthDay dtVigenciaInicial;
	private YearMonthDay dtVigenciaFinal;

	public FranqueadoFranquia() {
		super();
	}

	public FranqueadoFranquia(Long idFranqueadoFranquia, Franqueado franqueado,
			Franquia franquia, YearMonthDay dtVigenciaInicial,
			YearMonthDay dtVigenciaFinal) {
		this.idFranqueadoFranquia = idFranqueadoFranquia;
		this.franqueado = franqueado;
		this.franquia = franquia;
		this.dtVigenciaInicial = dtVigenciaInicial;
		this.dtVigenciaFinal = dtVigenciaFinal;
	}

	@Id
	@Column(name = "ID_FRANQUEADO_FRANQUIA", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "FRANQUEADO_FRANQUIA_SEQ")
	public Long getIdFranqueadoFranquia() {
		return this.idFranqueadoFranquia;
	}

	public void setIdFranqueadoFranquia(Long idFranqueadoFranquia) {
		this.idFranqueadoFranquia = idFranqueadoFranquia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_FRANQUEADO", nullable = false)
	public Franqueado getFranqueado() {
		return this.franqueado;
	}

	public void setFranqueado(Franqueado franqueado) {
		this.franqueado = franqueado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_FRANQUIA", nullable = false)
	public Franquia getFranquia() {
		return this.franquia;
	}

	public void setFranquia(Franquia franquia) {
		this.franquia = franquia;
	}

	@Column(name = "DT_VIGENCIA_INICIAL", nullable = false, length = 7)
	@Type(type = "com.mercurio.adsm.core.model.hibernate.JodaTimeYearMonthDayUserType")
	public YearMonthDay getDtVigenciaInicial() {
		return this.dtVigenciaInicial;
	}

	public void setDtVigenciaInicial(YearMonthDay dtVigenciaInicial) {
		this.dtVigenciaInicial = dtVigenciaInicial;
	}

	@Column(name = "DT_VIGENCIA_FINAL", nullable = false, length = 7)
	@Type(type = "com.mercurio.adsm.core.model.hibernate.JodaTimeYearMonthDayUserType")
	public YearMonthDay getDtVigenciaFinal() {
		return this.dtVigenciaFinal;
	}

	public void setDtVigenciaFinal(YearMonthDay dtVigenciaFinal) {
		this.dtVigenciaFinal = dtVigenciaFinal;
	}
}
