package com.mercurio.lms.franqueados.model;

// Generated 10/04/2014 15:18:12 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import com.mercurio.lms.municipios.model.Filial;

/**
 * Franquia generated by hbm2java
 */
@Entity
@Table(name = "FRANQUIA")
public class Franquia implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long idFranquia;
	private Filial filial;
	private List<FixoFranqueado> fixoFrqs = new ArrayList<FixoFranqueado>(0);
	private List<DoctoServicoFranqueado> doctoServicoFrqs = new ArrayList<DoctoServicoFranqueado>(0);
	private List<FranqueadoFranquia> franqueadoFranquias = new ArrayList<FranqueadoFranquia>(0);
	private List<ReembarqueDoctoServicoFranqueado> reembarqueDocServFrqs = new ArrayList<ReembarqueDoctoServicoFranqueado>(0);
	private List<MunicipioNaoAtendidoFranqueado> municipioNaoAtendFrqs = new ArrayList<MunicipioNaoAtendidoFranqueado>(0);

	public Franquia() {
		super();
	}

	public Franquia(Filial filial) {
		this.filial = filial;
	}

	public Franquia(Filial filial, List<FixoFranqueado> fixoFrqs,
			List<DoctoServicoFranqueado> doctoServicoFrqs,
			List<FranqueadoFranquia> franqueadoFranquias,
			List<ReembarqueDoctoServicoFranqueado> reembarqueDocServFrqs,
			List<MunicipioNaoAtendidoFranqueado> municipioNaoAtendFrqs) {
		this.filial = filial;
		this.fixoFrqs = fixoFrqs;
		this.doctoServicoFrqs = doctoServicoFrqs;
		this.franqueadoFranquias = franqueadoFranquias;
		this.reembarqueDocServFrqs = reembarqueDocServFrqs;
		this.municipioNaoAtendFrqs = municipioNaoAtendFrqs;
	}

	@Id
	@Column(name = "ID_FRANQUIA", unique = true, nullable = false)
	public Long getIdFranquia() {
		return this.idFranquia;
	}

	public void setIdFranquia(Long idFranquia) {
		this.idFranquia = idFranquia;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Filial getFilial() {
		return this.filial;
	}

	public void setFilial(Filial filial) {
		this.filial = filial;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "franquia")
	public List<FixoFranqueado> getFixoFrqs() {
		return this.fixoFrqs;
	}

	public void setFixoFrqs(List<FixoFranqueado> fixoFrqs) {
		this.fixoFrqs = fixoFrqs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "franquia")
	public List<FranqueadoFranquia> getFranqueadoFranquias() {
		return this.franqueadoFranquias;
	}

	public void setFranqueadoFranquias(
			List<FranqueadoFranquia> franqueadoFranquias) {
		this.franqueadoFranquias = franqueadoFranquias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "franquia")
	public List<MunicipioNaoAtendidoFranqueado> getMunicipioNaoAtendFrqs() {
		return this.municipioNaoAtendFrqs;
	}

	public void setMunicipioNaoAtendFrqs(
			List<MunicipioNaoAtendidoFranqueado> municipioNaoAtendFrqs) {
		this.municipioNaoAtendFrqs = municipioNaoAtendFrqs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "franquia")
	public List<DoctoServicoFranqueado> getDoctoServicoFrqs() {
		return this.doctoServicoFrqs;
	}

	public void setDoctoServicoFrqs(List<DoctoServicoFranqueado> doctoServicoFrqs) {
		this.doctoServicoFrqs = doctoServicoFrqs;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "franquia")
	public List<ReembarqueDoctoServicoFranqueado> getReembarqueDocServFrqs() {
		return this.reembarqueDocServFrqs;
	}

	public void setReembarqueDocServFrqs(
			List<ReembarqueDoctoServicoFranqueado> reembarqueDocServFrqs) {
		this.reembarqueDocServFrqs = reembarqueDocServFrqs;
	}

}
