package com.mercurio.lms.franqueados.model;

// Generated 10/04/2014 15:18:12 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.Type;
import org.joda.time.YearMonthDay;

import com.mercurio.adsm.framework.model.DomainValue;
import com.mercurio.lms.tabelaprecos.model.ParcelaPreco;

/**
 * GeneralidadeFrq generated by hbm2java
 */
@Entity
@Table(name = "GENERALIDADE_FRQ")
@SequenceGenerator(name = "GENERALIDADE_FRQ_SEQ", sequenceName = "GENERALIDADE_FRQ_SQ", allocationSize = 1)
public class GeneralidadeFranqueado implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private long idGeneralidadeFrq;
	private ParcelaPreco parcelaPreco;
	private DomainValue tpFrete;
	private BigDecimal pcParticipacao;
	private YearMonthDay dtVigenciaInicial;
	private YearMonthDay dtVigenciaFinal;

	public GeneralidadeFranqueado() {
	}

	public GeneralidadeFranqueado(long idGeneralidadeFrq, ParcelaPreco parcelaPreco,
			DomainValue tpFrete, BigDecimal pcParticipacao,
			YearMonthDay dtVigenciaInicial, YearMonthDay dtVigenciaFinal) {
		this.idGeneralidadeFrq = idGeneralidadeFrq;
		this.parcelaPreco = parcelaPreco;
		this.tpFrete = tpFrete;
		this.pcParticipacao = pcParticipacao;
		this.dtVigenciaInicial = dtVigenciaInicial;
		this.dtVigenciaFinal = dtVigenciaFinal;
	}

	@Id
	@Column(name = "ID_GENERALIDADE_FRQ", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GENERALIDADE_FRQ_SEQ")
	public long getIdGeneralidadeFrq() {
		return this.idGeneralidadeFrq;
	}

	public void setIdGeneralidadeFrq(long idGeneralidadeFrq) {
		this.idGeneralidadeFrq = idGeneralidadeFrq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PARCELA_PRECO", nullable = false)
	public ParcelaPreco getParcelaPreco() {
		return this.parcelaPreco;
	}

	public void setParcelaPreco(ParcelaPreco parcelaPreco) {
		this.parcelaPreco = parcelaPreco;
	}

	@Column(name = "TP_FRETE", nullable = false, length = 2)
	@Type(type = "com.mercurio.adsm.core.model.hibernate.DomainCompositeUserType", parameters = { @Parameter(name = "domainName", value = "DM_TIPO_FRETE_FRQ") })
	public DomainValue getTpFrete() {
		return this.tpFrete;
	}

	public void setTpFrete(DomainValue tpFrete) {
		this.tpFrete = tpFrete;
	}

	@Column(name = "PC_PARTICIPACAO", nullable = false, precision = 3, scale = 0)
	public BigDecimal getPcParticipacao() {
		return this.pcParticipacao;
	}

	public void setPcParticipacao(BigDecimal pcParticipacao) {
		this.pcParticipacao = pcParticipacao;
	}

	@Column(name = "DT_VIGENCIA_INICIAL", nullable = false, length = 7)
	@Type(type = "com.mercurio.adsm.core.model.hibernate.JodaTimeYearMonthDayUserType")
	public YearMonthDay getDtVigenciaInicial() {
		return this.dtVigenciaInicial;
	}

	public void setDtVigenciaInicial(YearMonthDay dtVigenciaInicial) {
		this.dtVigenciaInicial = dtVigenciaInicial;
	}

	@Column(name = "DT_VIGENCIA_FINAL", nullable = false, length = 7)
	@Type(type = "com.mercurio.adsm.core.model.hibernate.JodaTimeYearMonthDayUserType")
	public YearMonthDay getDtVigenciaFinal() {
		return this.dtVigenciaFinal;
	}

	public void setDtVigenciaFinal(YearMonthDay dtVigenciaFinal) {
		this.dtVigenciaFinal = dtVigenciaFinal;
	}

}
