package com.mercurio.lms.franqueados.model;

import java.math.BigDecimal;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.Type;
import org.joda.time.YearMonthDay;

import com.mercurio.adsm.framework.model.DomainValue;
import com.mercurio.lms.workflow.model.Pendencia;

/**
 * LancamentoFrq generated by hbm2java
 */
@Entity
@Table(name = "LANCAMENTO_FRQ", 
		uniqueConstraints = @UniqueConstraint(columnNames = {"ID_FRANQUIA", "ID_CONTA_CONTABIL_FRQ", "SG_DOCTO_INTERNACIONAL",
															"NR_DOCTO_INTERNACIONAL", "DT_COMPETENCIA", "CD_DOCTO_INTERNACIONAL" }))
@SequenceGenerator(name = "LANCAMENTO_FRQ_SEQ", sequenceName = "LANCAMENTO_FRQ_SQ", allocationSize = 1)
public class LancamentoFranqueado implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "ID_LANCAMENTO_FRQ", unique = true, nullable = false, precision = 10, scale = 0)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "LANCAMENTO_FRQ_SEQ")
	private Long idLancamentoFrq;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_FRANQUIA", nullable = false)
	private Franquia franquia;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CONTA_CONTABIL_FRQ", nullable = false)
	private ContaContabilFranqueado contaContabilFranqueado;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PENDENCIA")
	private Pendencia pendencia;
	
	@Column(name = "DT_COMPETENCIA", nullable = false, length = 7)
	@Type(type = "com.mercurio.adsm.core.model.hibernate.JodaTimeYearMonthDayUserType")
	private YearMonthDay dtCompetencia;
	
	@Column(name = "VL_LANCAMENTO", nullable = false, precision = 18)
	private BigDecimal vlLancamento;
	
	@Column(name = "NR_PARCELAS", precision = 2, scale = 0)
	private Integer nrParcelas;
	
	@Column(name = "TP_SITUACAO_PENDENCIA", nullable = false, length = 1)
	@Type(type = "com.mercurio.adsm.core.model.hibernate.DomainCompositeUserType", parameters = { @Parameter(name = "domainName", value = "DM_STATUS_WORKFLOW") })
	private DomainValue tpSituacaoPendencia = new DomainValue("E");
	
	@Column(name = "SG_DOCTO_INTERNACIONAL", length = 2)
	private String sgDoctoInternacional;
	
	@Column(name = "CD_DOCTO_INTERNACIONAL", precision = 4, scale = 0)
	private Short cdDoctoInternacional;
	
	@Column(name = "NR_DOCTO_INTERNACIONAL", precision = 6, scale = 0)
	private Integer nrDoctoInternacional;
	
	@Column(name = "OB_LANCAMENTO", length = 2000)
	private String obLancamento;
	
	@Column(name = "DS_LANCAMENTO", length = 500, nullable = false)
	private String dsLancamento;
	
	@Column(name = "VL_CONTABIL", precision = 18)
	private BigDecimal vlContabil;
	
	@OneToMany(mappedBy="lancamento",fetch = FetchType.LAZY,cascade={CascadeType.ALL})
	private List<AnexoLancamentoFranqueado> anexos;

	@Transient
	private boolean isManual = true;

	public LancamentoFranqueado() {
	}

	public Long getIdLancamentoFrq() {
		return this.idLancamentoFrq;
	}

	public void setIdLancamentoFrq(Long idLancamentoFrq) {
		this.idLancamentoFrq = idLancamentoFrq;
	}

	public Franquia getFranquia() {
		return this.franquia;
	}

	public void setFranquia(Franquia franquia) {
		this.franquia = franquia;
	}

	public ContaContabilFranqueado getContaContabilFranqueado() {
		return contaContabilFranqueado;
	}

	public void setContaContabilFranqueado(
			ContaContabilFranqueado contaContabilFranqueado) {
		this.contaContabilFranqueado = contaContabilFranqueado;
	}

	public Pendencia getPendencia() {
		return this.pendencia;
	}

	public void setPendencia(Pendencia pendencia) {
		this.pendencia = pendencia;
	}

	public YearMonthDay getDtCompetencia() {
		return this.dtCompetencia;
	}

	public void setDtCompetencia(YearMonthDay dtCompetencia) {
		this.dtCompetencia = dtCompetencia;
	}

	public BigDecimal getVlLancamento() {
		return this.vlLancamento;
	}

	public void setVlLancamento(BigDecimal vlLancamento) {
		this.vlLancamento = vlLancamento;
	}

	public DomainValue getTpSituacaoPendencia() {
		return this.tpSituacaoPendencia;
	}

	public void setTpSituacaoPendencia(DomainValue tpSituacaoPendencia) {
		this.tpSituacaoPendencia = tpSituacaoPendencia;
	}

	public String getSgDoctoInternacional() {
		return this.sgDoctoInternacional;
	}

	public void setSgDoctoInternacional(String sgDoctoInternacional) {
		this.sgDoctoInternacional = sgDoctoInternacional;
	}

	public Short getCdDoctoInternacional() {
		return this.cdDoctoInternacional;
	}

	public void setCdDoctoInternacional(Short cdDoctoInternacional) {
		this.cdDoctoInternacional = cdDoctoInternacional;
	}

	public Integer getNrDoctoInternacional() {
		return this.nrDoctoInternacional;
	}

	public void setNrDoctoInternacional(Integer nrDoctoInternacional) {
		this.nrDoctoInternacional = nrDoctoInternacional;
	}

	public String getObLancamento() {
		return this.obLancamento;
	}

	public void setObLancamento(String obLancamento) {
		this.obLancamento = obLancamento;
	}

	public boolean isManual() {
		return isManual;
	}

	public void setManual(boolean isManual) {
		this.isManual = isManual;
	}

	public String getDsLancamento() {
		return dsLancamento;
	}

	public void setDsLancamento(String dsLancamento) {
		this.dsLancamento = dsLancamento;
	}
	
	public List<AnexoLancamentoFranqueado> getAnexos() {
		return anexos;
	}

	public void setAnexos(List<AnexoLancamentoFranqueado> anexos) {
		this.anexos = anexos;
	}

	public Integer getNrParcelas() {
		return nrParcelas;
	}

	public void setNrParcelas(Integer nrParcelas) {
		this.nrParcelas = nrParcelas;
	}
	
	public BigDecimal getVlContabil() {
		return vlContabil;
	}

	public void setVlContabil(BigDecimal vlContabil) {
		this.vlContabil = vlContabil;
	}
	
}
