package com.mercurio.lms.franqueados.model;

// Generated 10/04/2014 12:11:11 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Type;
import org.joda.time.YearMonthDay;

/**
 * ReembarqueFrq generated by hbm2java
 */
@Entity
@Table(name = "REEMBARQUE_FRQ")
@SequenceGenerator(name = "REEMBARQUE_FRQ_SEQ", sequenceName = "REEMBARQUE_FRQ_SQ", allocationSize = 1)
public class ReembarqueFranqueado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5935326845774264654L;
	
	private long idReembarqueFrq;
	private BigDecimal pcTonelada;
	private BigDecimal vlCte;
	private YearMonthDay dtVigenciaInicial;
	private YearMonthDay dtVigenciaFinal;

	public ReembarqueFranqueado() {
	}

	public ReembarqueFranqueado(long idReembarqueFrq, BigDecimal pcTonelada,
			BigDecimal vlCte, YearMonthDay dtVigenciaInicial,
			YearMonthDay dtVigenciaFinal) {
		this.idReembarqueFrq = idReembarqueFrq;
		this.pcTonelada = pcTonelada;
		this.vlCte = vlCte;
		this.dtVigenciaInicial = dtVigenciaInicial;
		this.dtVigenciaFinal = dtVigenciaFinal;
	}

	@Id
	@Column(name = "ID_REEMBARQUE_FRQ", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "REEMBARQUE_FRQ_SEQ")
	public long getIdReembarqueFrq() {
		return this.idReembarqueFrq;
	}

	public void setIdReembarqueFrq(long idReembarqueFrq) {
		this.idReembarqueFrq = idReembarqueFrq;
	}

	@Column(name = "PC_TONELADA", nullable = false, precision = 5, scale = 2)
	public BigDecimal getPcTonelada() {
		return this.pcTonelada;
	}

	public void setPcTonelada(BigDecimal pcTonelada) {
		this.pcTonelada = pcTonelada;
	}

	@Column(name = "VL_CTE", nullable = false, precision = 18, scale = 2)
	public BigDecimal getVlCte() {
		return this.vlCte;
	}

	public void setVlCte(BigDecimal vlCte) {
		this.vlCte = vlCte;
	}

	@Column(name = "DT_VIGENCIA_INICIAL", nullable = false, length = 7)
	@Type(type = "com.mercurio.adsm.core.model.hibernate.JodaTimeYearMonthDayUserType")
	public YearMonthDay getDtVigenciaInicial() {
		return this.dtVigenciaInicial;
	}

	public void setDtVigenciaInicial(YearMonthDay dtVigenciaInicial) {
		this.dtVigenciaInicial = dtVigenciaInicial;
	}

	@Column(name = "DT_VIGENCIA_FINAL", nullable = false, length = 7)
	@Type(type = "com.mercurio.adsm.core.model.hibernate.JodaTimeYearMonthDayUserType")
	public YearMonthDay getDtVigenciaFinal() {
		return this.dtVigenciaFinal;
	}

	public void setDtVigenciaFinal(YearMonthDay dtVigenciaFinal) {
		this.dtVigenciaFinal = dtVigenciaFinal;
	}

}
