package com.mercurio.lms.sgr.action;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.mercurio.adsm.framework.model.ResultSetPage;
import com.mercurio.adsm.framework.report.ReportExecutionManager;
import com.mercurio.adsm.framework.util.TypedFlatMap;
import com.mercurio.lms.contratacaoveiculos.model.service.MeioTransporteService;
import com.mercurio.lms.contratacaoveiculos.model.service.OperadoraMctService;
import com.mercurio.lms.contratacaoveiculos.model.service.ProprietarioService;
import com.mercurio.lms.municipios.model.service.FilialService;
import com.mercurio.lms.sgr.model.service.SolicitacaoSinalService;
import com.mercurio.lms.sgr.report.ConsultarSolicitacoesSinalService;
import com.mercurio.lms.util.PessoaUtils;

/**
 * Generated by: ADSM ActionGenerator
 *  
 * Não inserir documentação após ou remover a tag do XDoclet a seguir.
 * O valor do <code>id</code> informado abaixo deve ser utilizado para referenciar este serviço.
 * @spring.bean id="lms.sgr.consultarSolicitacoesSinalAction"
 */

public class ConsultarSolicitacoesSinalAction {
	private SolicitacaoSinalService solicitacaoSinalService;
	private FilialService filialService;
	private OperadoraMctService operadoraMctService;
	private MeioTransporteService meioTransporteService;
	private ProprietarioService proprietarioService;
	private ReportExecutionManager reportExecutionManager;
	private ConsultarSolicitacoesSinalService consultarSolicitacoesSinalService;
	
	/**
	 * Declaração serviço principal da Action.
	 */
	public void setConsultarSolicitacoesSinalService(ConsultarSolicitacoesSinalService consultarSolicitacoesSinalService) {
		this.consultarSolicitacoesSinalService = consultarSolicitacoesSinalService;
	}		
	
	public void setReportExecutionManager(
			ReportExecutionManager reportExecutionManager) {
		this.reportExecutionManager = reportExecutionManager;
	}

	public List findLookupFilial(Map criteria) {		
		return this.getFilialService().findLookup(criteria);
	}

	public List findLookupOperadoraMCT(Map criteria) {
		Map pessoa = (Map)criteria.get("pessoa");
		pessoa.put("nrIdentificacao", PessoaUtils.validateIdentificacao((String)pessoa.get("nrIdentificacao")));
		return this.getOperadoraMctService().findLookup(criteria);
	}

	public List findLookupMeioTransporte(Map criteria) {		
		return this.getMeioTransporteService().findLookup(criteria);
	}

	public List findLookupProprietario(Map criteria) {		
		return this.getProprietarioService().findLookup(criteria);
	}

    public ResultSetPage findPaginatedBySolicitacaoSinal(TypedFlatMap criteria) {
    	ResultSetPage rspSolicitacaoSinal = this.getSolicitacaoSinalService().findPaginatedBySolicitacaoSinal(criteria);

    	List listSolicitacaoSinal = new ArrayList();
    	for(int i=0; i< rspSolicitacaoSinal.getList().size(); i++) {
    		Map mapSolicitacaoSinal = (HashMap) rspSolicitacaoSinal.getList().get(i);   		    		
    		mapSolicitacaoSinal.put("sgFilialOrigem", (String)((Map)mapSolicitacaoSinal.get("filial")).get("sgFilial"));
    		listSolicitacaoSinal.add(mapSolicitacaoSinal);
    	}
    	
    	rspSolicitacaoSinal.setList(listSolicitacaoSinal);
    	
    	return rspSolicitacaoSinal; 
    }

    public Integer getRowCountBySolicitacaoSinal(TypedFlatMap criteria) {
    	return this.getSolicitacaoSinalService().getRowCountBySolicitacaoSinal(criteria);
    }
    
    public String execute(TypedFlatMap params) throws Exception {
    	return this.reportExecutionManager.generateReportLocator(this.consultarSolicitacoesSinalService, params);
    }
    
	public SolicitacaoSinalService getSolicitacaoSinalService() {
		return solicitacaoSinalService;
	}
	public void setSolicitacaoSinalService(
			SolicitacaoSinalService solicitacaoSinalService) {
		this.solicitacaoSinalService = solicitacaoSinalService;
	}		
	public FilialService getFilialService() {
		return filialService;
	}
	public void setFilialService(FilialService filialService) {
		this.filialService = filialService;
	}
	public MeioTransporteService getMeioTransporteService() {
		return meioTransporteService;
	}
	public void setMeioTransporteService(MeioTransporteService meioTransporteService) {
		this.meioTransporteService = meioTransporteService;
	}
	public OperadoraMctService getOperadoraMctService() {
		return operadoraMctService;
	}
	public void setOperadoraMctService(OperadoraMctService operadoraMctService) {
		this.operadoraMctService = operadoraMctService;
	}
	public ProprietarioService getProprietarioService() {
		return proprietarioService;
	}
	public void setProprietarioService(ProprietarioService proprietarioService) {
		this.proprietarioService = proprietarioService;
	}

}
