package com.mercurio.lms.configuracoes.action;

import java.util.List;

import com.mercurio.adsm.framework.model.CrudAction;
import com.mercurio.lms.configuracoes.model.Frequencia;
import com.mercurio.lms.configuracoes.model.service.FrequenciaService;

import com.mercurio.adsm.framework.annotations.ParametrizedAttribute;

/**
 * Generated by: ADSM ActionGenerator
 *  
 * Não inserir documentação após ou remover a tag do XDoclet a seguir.
 * O valor do <code>id</code> informado abaixo deve ser utilizado para referenciar este serviço.
 * @spring.bean id="lms.configuracoes.manterFrequenciasAction"
 */

public class ManterFrequenciasAction extends CrudAction {
	public void setFrequencia(FrequenciaService frequenciaService) {
		this.defaultService = frequenciaService;
	}
    public void removeById(java.lang.Long id) {
        ((FrequenciaService)defaultService).removeById(id);
    }

	/**
	 *
	 */
	@ParametrizedAttribute(type = java.lang.Long.class)
    public void removeByIds(List ids) {
    	((FrequenciaService)defaultService).removeByIds(ids);
    }

    public Frequencia findById(java.lang.Long id) {
    	return ((FrequenciaService)defaultService).findById(id);
    }

}
