package com.mercurio.lms.vendas.util;

public interface ConstantesVendas {

	String CLIENTE_ESPECIAL = "S";
	String CLIENTE_EVENTUAL = "E";
	String CLIENTE_FILIAL = "F";
	String CLIENTE_POTENCIAL = "P";
	
	String SITUACAO_INCOMPLETO = "N";
	String SITUACAO_INATIVO = "I";
	String SITUACAO_ATIVO = "A";

	String COTACAO = "COT";
	String COTACAO_IN_SESSION = "COTACAO_IN_SESSION";
	String DIAS_VALIDADE_COTACAO = "DIAS_VALIDADE_COTACAO";
	String NR_ULTIMA_COTACAO = "ULTIMA_COTACAO";
	String FIND_COTACAO_BY_ID = "com.mercurio.lms.vendas.model.Cotacao.findCotacaoById";
	String SIMULACAO_IN_SESSION = "SIMULACAO_IN_SESSION";
	String NR_CASAS_DECIMAIS_PESO = "NR_CASAS_DECIMAIS_PESO";
	String PG_PRIORIDADE_EVENTO_WORKFLOW = "PRIORIDADE_EVENTO_WORKFLOW";

	String ESPECIAL_PARA_PONTENCIAL_OU_EVENTUAL = "EPE";
	String FILIAL_PARA_PONTENCIAL_OU_EVENTUAL = "FPE";
	String FILIAL_PARA_ESPECIAL = "FE";
	
	//Servico adicional
	String TP_INDICADOR_DESCONTO = "D";
	String TP_INDICADOR_VALOR = "V";

	/* Tipos do Rodo */
	String TP_PROPOSTA_CAPITAL_INTERIOR_PERCENTUAL = "P";
	String TP_PROPOSTA_CAPITAL_INTERIOR = "C";
	String TP_PROPOSTA_TARIFA = "T";
	
	/* Tipos do Aéreo*/
	String TP_PROPOSTA_PROMOCIONAL = "O";
	String TP_PROPOSTA_MINIMO_MAIS_EXCEDENTE = "M";
	String TP_PROPOSTA_MINIMO_MAIS_VALOR_KG = "I";
	String TP_PROPOSTA_CONVENCIONAL = "V";
	
	String TP_SITUACAO_APROVADO = "A";
	String TP_SITUACAO_REPROVADO = "R";
	String TP_SITUACAO_CANCELADO = "C";
	String TP_SITUACAO_EM_APROVACAO = "E";
	String TP_SITUACAO_INCLUIDO = "I";
	
	Short ID_WORKFLOW_ALTERACAO_FATOR_CUBAGEM_AEREO = 3041;

	String REMDEST = "REMDEST";
	String TOM = "TOM";
	
}
