package com.mercurio.lms.expedicao.util;

import java.util.Arrays;
import java.util.List;

import com.mercurio.lms.util.LongUtils;

public interface ConstantesExpedicao {

	//EDI Opcao Processamento
	String EDI_PROCESSAR_AUTOMATICO = "1";
	String EDI_PROCESSAR_NOTAS_FISCAIS = "2";
	String EDI_PROCESSAR_NOTAS_FISCAIS_ETIQUETAS = "3";
	//Servico
	String RODOVIARIO_NACIONAL_CONVENCIONAL = "RNC";
	String RODOVIARIO_NACIONAL_EMERGENCIAL = "RNE";
	String AEREO_NACIONAL_CONVENCIONAL = "ANC";
	//Modais
	String MODAL_AEREO = "A";
	String MODAL_RODOVIARIO = "R";
	//Abrangências
	String ABRANGENCIA_INTERNACIONAL = "I";
	String ABRANGENCIA_NACIONAL = "N";
	//Tipos de Processamento
	String TP_PROCESSAMENTO_AUTOMATICO = "A";
	String TP_PROCESSAMENTO_POR_NOTA_FISCAL = "P";
	String TP_PROCESSAMENTO_POR_INTERVALO_NOTAS_FISCAIS = "I";
	String TP_PROCESSAMENTO_POR_DOCTO_CLIENTE = "E";
	String TP_PROCESSAMENTO_POR_CCE = "C";
	String TP_PROCESSAMENTO_POR_MANIFESTO_CONSOLIDADO = "M";
	//MonitoramentoDescarga
	String TP_SITUACAO_DESCARGA_FINALIZADA = "M";
	String TP_SITUACAO_DESCARGA_FINALIZADA_ERRO = "P";
	String TP_SITUACAO_DESCARGA_INICIADA = "G";
	String TP_SITUACAO_DESCARGA_PROCESSAMENTO_EDI_INICIADO = "Y";
	String TP_SITUACAO_DESCARGA_DIGITACAO_NOTAS_FISCAIS_INICIADA = "V";
	String TP_SITUACAO_DESCARGA_DIGITACAO_NOTAS_FISCAIS_FINALIZADA = "D";
	String TP_SITUACAO_DESCARGA_EMISSAO_CONHECIMENTO_REALIZADA = "S";
	String TP_SITUACAO_DESCARGA_EMISSAO_CONHECIMENTO_INICIADA = "Q";
	String TP_SITUACAO_DESCARGA_TODOS_VOLUMES_AFERIDOS = "J";
	
	//Tipos de conhecimentos
	String CONHECIMENTO_COMPLEMENTO_FRETE = "CF";
	String CONHECIMENTO_COMPLEMENTO_ICMS = "CI";
	String CONHECIMENTO_DEVOLUCAO = "DE";
	String CONHECIMENTO_DEVOLUCAO_PARCIAL = "DP";
	String CONHECIMENTO_NORMAL = "NO";
	String CONHECIMENTO_REENTREGA = "RE";
	String CONHECIMENTO_REFATURAMENTO = "RF";
	String CONHECIMENTO_SUBSTITUTO = "SU";
	//Tipos de Controle de Carga
	String TP_CONTROLE_CARGA_VIAGEM = "V";
	String TP_CONTROLE_CARGA_COLETA_ENTREGA = "C";
	//Tipos de Manifestos
	String TP_MANIFESTO_VIAGEM = "V";
	String TP_MANIFESTO_ENTREGA = "E";
	
	//Tipos de Manifestos de Entrega
	String TP_MANIFESTO_ENTREGA_ENTREGA_PARCEIRA = "EP";
	String TP_MANIFESTO_ENTREGA_NORMAL = "EN";
	String TP_MANIFESTO_ENTREGA_DIRETA = "ED";
	//Status Manifesto
	String TP_STATUS_MANIFESTO_AGUARDANDO_DESCARGA = "AD";
	String TP_STATUS_MANIFESTO_EMITIDO = "ME";
	String TP_STATUS_MANIFESTO_EM_ESCALA_FILIAL = "EF";
	String TP_STATUS_MANIFESTO_EM_VIAGEM = "EV";
	String TP_STATUS_MANIFESTO_CANCELADO = "CA";
	String TP_STATUS_MANIFESTO_COLETA_ENTREGA = "TC";
	String TP_STATUS_MANIFESTO_CARREGAMENTO_CONCLUIDO = "CC";

	//Constantes evento
	Short CD_EVENTO_PRE_MANIFESTO = 62;

	//Tipos Eventos Manifesto
	String TP_EVENTO_MANIFESTO_FIM_CARREGAMENTO = "FC";

	//Tipos Eventos de Controle de Carga
	String TP_EVENTO_CONTROLE_CARGA_FIM_CARREGAMENTO = "FC";	
	String TP_EVENTO_CONTROLE_CARGA_INICIO_DESCARGA = "ID";
	//Tipos Status
	String TP_STATUS_CANCELADO = "C";
	String TP_STATUS_PRE_AWB = "P";
	//Tipos de cálculo
	String CALCULO_CORTESIA = "G";
	String CALCULO_COTACAO = "C";
	String CALCULO_MANUAL = "M";
	String CALCULO_NORMAL = "N";
	//Tipo Cliente
	String TP_CLIENTE_ESPECIAL = "S";
    String TP_CLIENTE_FILIAL = "F";
    String TP_CLIENTE_POTENCIAL = "P";
    String TP_CLIENTE_EVENTUAL = "E";
	//Tipo Frete
	String TP_FRETE_CIF = "C";
	String TP_FRETE_FOB = "F";
	String TP_FRETE_PACOTINHO = "P";
	//Tipo Devedor Frete
	String TP_DEVEDOR_OUTRO_RESPONSAVEL = "O";
	String TP_DEVEDOR_DESTINATARIO = "D";
	String TP_DEVEDOR_REMETENTE = "R";
	String TP_DEVEDOR_REDESPACHO = "P";
	String TP_DEVEDOR_CONSIGNATARIO = "C";
	//Tipo Documento Servico
	String PRE_CONHECIMENTO_NACIONAL = "PRE_CTR";
	String CONHECIMENTO_NACIONAL = "CTR";
	String CONHECIMENTO_ELETRONICO = "CTE";
	String CONHECIMENTO_INTERNACIONAL = "CRT";
	String NOTA_FISCAL_SERVICO = "NFS";
	String NOTA_FISCAL_SERVICO_ELETRONICA = "NSE";
	String NOTA_FISCAL_TRANSPORTE_ELETRONICA = "NTE";
	String NOTA_FISCAL_TRANSPORTE = "NFT";
	String MINUTA_DESPACHO_ACOMPANHAMENTO = "MDA";
	String RECIBO_REEMBOLSO = "RRE";
	String NOTA_DEBITO_NACIONAL = "NDN";
	String MANIFESTO_ITERNACIONAL_CARGA = "MIC";
	String MANIFESTO_ITERNACIONAL_CARGA_DTA = "MIC_DTA";
	String PRE_AWB = "PRE_AWB"; 
	String TP_STATUS_AWB_EMITIDO = "E"; 
	String AIRWAY_BILL = "AWB"; 
	String ORDEM_SERVICO = "OS"; 

	//Tipo Peso Calcula
	String TP_PESO_CALCULO_AUTOMATICO = "A";
	String TP_PESO_CALCULO_CUBADO = "C";
	String TP_PESO_CALCULO_DECLARADO = "D";
	String TP_PESO_CALCULO_AFERIDO = "F";
	String TP_PESO_CALCULO_CUBADO_AFERIDO = "E";
	// LMS-6531
	String TP_PESO_CALCULO_CUBADO_DECLARADO = "G";
	String TP_PESO_CALCULO_AUTOMATICO_AFERIDO = "H";
	String TP_PESO_CALCULO_AUTOMATICO_DECLARADO = "I";
	String TP_PESO_CALCULO_AUTOMATICO_CUBADO_DECLARADO = "J";

	// Tipo Origem Peso
	String TP_ORIGEM_PESO_AUTOMACAO = "A";
	String TP_ORIGEM_PESO_MANUAL = "M";
	String TP_ORIGEM_PESO_AUTOMATICA_MANUAL = "B";

	//Tipo de situações do manifesto eletrônico
	String TP_MDFE_ENVIADO = "E"; 
	String TP_MDFE_AUTORIZADO = "A"; 
	String TP_MDFE_REJEITADO = "R"; 
	String TP_MDFE_CANCELADO_ENVIADO = "B"; 
	String TP_MDFE_CANCELADO = "C"; 
	String TP_MDFE_CANCELADO_REJEITADO = "D"; 
	String TP_MDFE_ENCERRADO_ENVIADO = "F"; 
	String TP_MDFE_ENCERRADO = "G"; 
	String TP_MDFE_ENCERRADO_REJEITADO = "H"; 
	String TP_MDFE_ENVIADO_CONTINGENCIA = "T"; 
	
	
	//Session
	String AWB_IN_SESSION = "AWB_IN_SESSION";
	String CALCULO_SERVICO_IN_SESSION = "CALCULO_SERVICO_IN_SESSION";
	String CLIENTE_CONSIGNATARIO_IN_SESSION = "CLIENTE_CONSIGNATARIO_IN_SESSION";
	String CLIENTE_REDESPACHO_IN_SESSION = "CLIENTE_REDESPACHO_IN_SESSION";
	String CLIENTE_RESPONSAVELFRETE_IN_SESSION = "CLIENTE_RESPONSAVELFRETE_IN_SESSION";
	String TP_DOCUMENTO_IN_SESSION = "TP_DOCUMENTO_IN_SESSION";
	String CONHECIMENTO_IN_SESSION = "CONHECIMENTO_IN_SESSION";
	String CONHECIMENTO_PERSISTENT_IN_SESSION = "CONHECIMENTO_PERSISTENT_IN_SESSION";
	String CONHECIMENTOS_IN_SESSION = "CONHECIMENTOS_IN_SESSION";
	String CTOs_AWB_IN_SESSION = "CTOs_AWB_IN_SESSION";
	String ID_DOCTO_SERVICO_IN_SESSION = "ID_DOCTO_SERVICO_IN_SESSION";
	String NOTA_FISCAL_SERVICO_IN_SESSION = "NFS_IN_SESSION";
	String OBSERVACOES_IN_SESSION = "OBSERVACOES_IN_SESSION";
	String OBSERVACAO_COTACAO_ERRO_IN_SESSION = "OBSERVACAO_COTACAO_ERRO_IN_SESSION";
	String SERV_ADICIONAL_IN_SESSION = "SERV_ADICIONAL_IN_SESSION";
	String CTO_INTERNACIONAL_IN_SESSION = "CTO_INTERNACIONAL_IN_SESSION";
	String NR_PROXIMO_FORMULARIO_IN_SESSION = "NR_PROXIMO_FORMULARIO_IN_SESSION";

	//Documento Servico
	String IE_REDESPACHO = "IE_REDESPACHO";
	String IE_RESPONSAVEL_FRETE = "IE_RESPONSAVEL_FRETE";
	String IE_CONSIGNATARIO = "IE_CONSIGNATARIO";
	String PRE_CONHECIMENTO = "P";
	String DOCUMENTO_SERVICO_GERADO = "G";
	String DOCUMENTO_SERVICO_EMITIDO = "E";
	String DOCUMENTO_SERVICO_CANCELADO = "C";

	//DM_TIPO_OPERACAO_EMISSAO
	String CD_EMISSAO = "E";
	String CD_REEMISSAO = "R";
	String CD_REENVIO_SOM = "S";
	String CD_EMISSAO_NFT = "N";
	String CD_REEMISSAO_NFT = "M";
	String CD_REEMISSAO_NTE = "P";
	String CD_GERACAO_CTE = "H";
	String CD_REEMISSAO_CTE = "Q";

	//DM_OPCAO_EMISSAO
	String CD_OPCAO_EMISSAO_CONHECIMENTO = "P";
	String CD_OPCAO_EMISSAO_VEICULO = "V";
	String CD_OPCAO_EMISSAO_FATURA = "F";
	String CD_OPCAO_EMISSAO_CLIENTE = "C";

	//Parametros Gerais
	String CALCULADO_ATE_DESTINO = "O DESTINO";
	String DIAS_VALIDADE_NF = "DIAS_VALIDADE_NF";
	String DIAS_GERACAO_FALT = "DIAS_GERACAO_FALT";
	String DS_ESPECIE_VOLUME = "VOLS";
	String ID_LOCA_DOC_CANCELADO = "ID_LOCA_DOC_CANCELADO";
	String ID_EMPRESA_MERCURIO = "ID_EMPRESA_MERCURIO";
	String ID_NATUREZA_PRODUTO_PADRAO = "ID_NATUREZA_PRODUTO_PADRAO";
	String ID_SERVICO_TRIBUTO_NFT = "ID_SERVICO_TRIBUTO_NFT";
	String JUST_INUT_CTE = "JUST_INUT_CTE";
	String KM_MAX_RELATORIO_CO2 = "KM_MAX_RELATORIO_CO2"; 
	String KM_MIN_RELATORIO_CO2 = "KM_MIN_RELATORIO_CO2";
	String LIMITE_NFS_CTRC = "LIMITE_NFS_CTRC";
	String NM_PARAMETRO_LIMITE_PESO_CORTESIA = "LIMITE_PESO_CORTESIA";
	String NM_PARAMETRO_LIMITE_PESO_CUBADO_CORTESIA = "LIMITE_PESO_CUBADO_CORTESIA";
	String NM_PARAMETRO_LIMITE_VALOR_MERCADORIA = "VLR_LIMITE_MERCADORIA";
	String NM_PARAMETRO_LIMITE_PESO_CTRC = "PESO_LIMITE_CTRC";
	String NM_PARAMETRO_LIMITE_PESO_VOLUME = "LIMITE_PESO_VOLUME";
	String NM_PARAMETRO_RELACAO_VL_FRETE_MERCADORIA = "RELACAO_VL_FRETE_MERCADORIA";
	String NM_PARAMETRO_LIMITE_PESO_VOLUME_CALCULO_FRETE = "LIMITE_PESO_VOLUME_CALCULO_FRETE";
	String NM_PARAMETRO_LIMITE_DIFERENCA_PESO = "DIF_PESO_DECLARADO_AFERIDO";
	String NM_PARAMETRO_PESO_METRAGEM_CUBICA_RODOVIARIO = "PESO_METRAGEM_CUBICA_RODOVIARIO";
	String NM_PARAMETRO_PESO_METRAGEM_CUBICA_AEREO = "PESO_METRAGEM_CUBICA_AEREO";
	String NM_PARAMETRO_IMPRIME_NF_TRANSP = "IMPRIME_NF_TRANSP";
	String NM_PARAMETRO_VLR_LIMITE_FRETE = "VLR_LIMITE_FRETE";
	String NM_PARAMETRO_VLR_MINIMO_FRETE = "VLR_MINIMO_FRETE";
	String NM_PARAMETRO_RELACAO_FRETE_MERCADORIA = "RELACAO_FRETE_MERCADORIA";
	String NM_PARAMETRO_OBSERVACAO_GERAL = "OBSERVACAO_GERAL";
	String NM_PARAMETRO_DS_PRODUTO_PERIGOSO = "DS_PRODUTO_PERIGOSO";
	String NM_PARAMETRO_DS_PRODUTO_CONTROLADO = "DS_PRODUTO_CONTROLADO";
	String NM_PARAMETRO_OBSERVACAO_COTACAO_ERRO = "OBSERVACAO_COTACAO_ERRO";
	String NM_PARAMETRO_OBSERVAÇÃO_CTE_SUBCONTRATANTE = "OBSERVACAO_CTE_SUBCONTRATANTE";
	String NR_MINIMO_DIAS_ARMAZENAGEM = "MINIMO_DIAS_ARMAZENAGEM";
	String PC_ADVALOREM_ARMAZENAGEM = "PC_ADVALOREM_ARMAZENAGEM";
	String PC_COBRANCA_DEVOLUCAO = "PercentualCobrancaDevolucao";
	String PC_COBRANCA_REENTREGA = "PercentualCobrancaReentrega";
	String PC_DESCONTO_FRETE_CORTESIA = "DESCONTO_FRETE_CORTESIA";
	String PC_DESCONTO_FRETE_TOTAL = "DESCONTO_FRETE_TOTAL";
	String VLR_MINIMO_FRETE_CORTESIA = "VLR_MINIMO_FRETE_CORTESIA";
	String VLR_MINIMO_FRETE_PESO = "VLR_MINIMO_FRETE";
	String NM_PARAMETRO_IMPRIME_NF_MODELO3 = "IMPRIME_NFT_MODELO3";
	String NM_PARAMETRO_FATOR_CUBAGEM_PADRAO_RODO = "FATOR_CUBAGEM_PADRAO_RODO";
	String NM_PARAMETRO_FATOR_CUBAGEM_PADRAO_AEREO = "FATOR_CUBAGEM_PADRAO_AEREO";
	String NM_PARAMETRO_DESCONTO_USO_EQUIPAMENTO = "PC_DESCONTO_USO_EQUIPE_MERCURIO";
	String QTDE_REENVIOS_CTE = "QTDE_REENVIOS_CTE";
	String NM_PARAMETRO_LIMITE_GERAL_VL_MERCADORIA = "LIMITE_GERAL_VL_MERCADORIA";
	String NM_PARAMETRO_LIMITE_GERAL_VL_FRETE = "LIMITE_GERAL_VL_FRETE";
	String NM_PARAMETRO_PERCENTUAL_GERAL_VL_MERCADORIA = "PERCENTUAL_GERAL_VL_MERCADORIA";
	String NM_PARAMETRO_LIMITE_GERAL_MIN_VL_FRETE = "LIMITE_GERAL_MIN_VL_FRETE";
	String CNPJ_GERA_OCORREN_FEDEX = "GERA_OCORREN_FEDEX";
	String CNPJ_GERA_OCORREN_FEDEX_SUB = "GERA_OCORREN_FEDEX_SUB";
    String NM_PARAMETRO_VL_LIMITE_PESO_VOL = "VL_LIMITE_PESO_VOL";
    String NM_PARAMETRO_VL_LIMITE_PESO_CUB = "VL_LIMITE_PESO_CUB";
    String NM_PARAMETRO_VL_LIMITE_PS_CUB_VOL = "VL_LIMITE_PS_CUB_VOL";
    String NM_PARAMETRO_VL_LIMITE_QTDE_VOL = "VL_LIMITE_QTDE_VOL";
	String NM_PARAMETRO_CD_OCORRENCIA_BLOQ_DIFAL = "CD_OCORRENCIA_BLOQ_DIFAL";
	String NM_PARAMETRO_CD_OCORRENCIA_LIB_DIFAL = "CD_OCORRENCIA_LIB_DIFAL";

	//Parâmetros de Filiais
	String NM_PARAMETRO_FILIAL_LIMITE_VL_MERCADORIA = "LIMITE_VL_MERCADORIA";
	String NM_PARAMETRO_FILIAL_LIMITE_VL_FRETE = "LIMITE_VL_FRETE";
	String NM_PARAMETRO_FILIAL_PERCENTUAL_VL_MERC = "PERCENTUAL_VL_MERC";
	String NM_PARAMETRO_FILIAL_LIMITE_MIN_VL_FRETE = "LIMITE_MIN_VL_FRETE";

	//Parcelas de Preco
	String TP_SERVICO_ADICIONAL = "S";
	String TP_GENERALIDADE = "G";

	String CD_ADVALOREM = "IDAdvalorem";
	String CD_ADVALOREM_1 = "IDAdvalorem1";
	String CD_ADVALOREM_2 = "IDAdvalorem2";
	String CD_FRETE_PESO = "IDFretePeso";
	String CD_FRETE_QUILO = "IDFreteQuilo";
	String CD_FRETE_VALOR = "IDFreteValor";
	String CD_SEGURO_FLUVIAL = "IdSeguroFluvial";
	String CD_DESCONTO = "IDDesconto";	
	String CD_TARIFA_MINIMA = "IDTarifaMinima";
	String CD_TAXA_COLETA_INTERIOR_CONVENCIONAL = "IDColetaInteriorConvencional";
	String CD_TAXA_COLETA_INTERIOR_EMERGENCIA = "IDColetaInteriorEmergencia";
	String CD_TAXA_COLETA_URBANA_CONVENCIONAL = "IDColetaUrbanaConvencional";
	String CD_TAXA_COLETA_URBANA_EMERGENCIA = "IDColetaUrbanaEmergencia";
	String CD_TAXA_COMBUSTIVEL = "IDTaxaCombustivel";
	String CD_TAXA_ENTREGA_INTERIOR_CONVENCIONAL = "IDEntregaInteriorConvencional";
	String CD_TAXA_ENTREGA_INTERIOR_EMERGENCIA = "IDEntregaInteriorEmergencia";
	String CD_TAXA_ENTREGA_URBANA_CONVENCIONAL = "IDEntregaUrbanaConvencional";
	String CD_TAXA_ENTREGA_URBANA_EMERGENCIA = "IDEntregaUrbanaEmergencia";
	String CD_TAXA_TERRESTRE = "IDTaxaTerrestre";
	String CD_OUTROS = "IDOutros";
	Integer QTDE_MINIMA_PARES_SAPATOS = 30;
	//Generalidades
	String CD_CAT = "IDCat";
	String CD_DESPACHO = "IDDespacho";
	String CD_GRIS = "IDGris";
	String CD_TAXA_FLUVIAL = "IDTaxaFluvial";
	String CD_TAXA_FLUVIAL_BALSA = "IDTSB";
	String CD_TRT = "IdTrt";
	String CD_ITR = "IDItr";
	String CD_PEDAGIO = "IDPedagio";
	String CD_VEICULO_DEDICADO = "IDVeiculoDedicado";
	String CD_AGENDAMENTO_COLETA_ENTREGA = "IDAgendamentoColetaEntrega";
	String CD_TAXA_PALETIZACAO = "IDTaxaPaletizacao";
	String CD_CUSTO_DESCARGA = "IDCustoDescarga";
	String CD_MINIMO_REENTREGA = "IDMinimoReentrega";


	String CD_PEDAGIO_DOCUMENTO = "IdPedagioDocumento";
	String CD_PEDAGIO_FAIXA_PESO = "IdPedagioFaixaPeso";
	String CD_PEDAGIO_FRACAO = "IdPedagioFracao";
	String CD_PEDAGIO_POSTO_FRACAO = "IdPedagioPostoFracao";
	String CD_REFATURAMENTO = "IdRefaturamento";	
	String CD_SEGURANCA_ADICIONAL = "IDSegurancaAdicional";
	String CD_SEGURO_CARGA_PERMANENCIA = "IdSegPerm";
	String CD_TAD = "IDTad";
	String CD_TAS = "IDTas";
	String CD_TDE = "IDTde";
	String CD_TAXA_EXPEDIENTE = "IDTaxaExpediente";
	String CD_TAXA_SUFRAMA = "IDTaxaSuframa";
	String CD_SUFRAMA = "IDSuframa";
	String CD_TRANSFERENCIA = "IDTransferencia";
	String CD_TOTAL_FRETE = "IDTotalFrete";
	String CD_ESTADIA_34 = "IDEstadia3/4";
	
	String CD_EMEX = "IdEmex";
	
	//Servicos Adicionais
	String CD_AGENDAMENTO_COLETA = "IDAgendamentoColeta";
	String CD_AGENDAMENTO_ENTREGA = "IDAgendamentoEntrega";
	String CD_AGENDAMENTO_ENTREGA_SAB_DOM_FER = "IDAgendamentoEntregaSDF";
	String CD_ARMAZENAGEM = "IDArmazenagem";
	String CD_COMPROVANTE_ENTREGA = "IDComprovanteEntrega";
	String CD_ENTREGA_HORARIO_ESPECIAL = "IDEntregaHorarioEspecial";
	String CD_ESCOLTA = "IDEscolta";
	String CD_ESTADIA_VEICULO = "IDEstadiaVeiculo";
	String CD_ESTADIA_TRUCK = "IDEstadiaTruck";
	String CD_ESTADIA_CONJUNTO = "IdEstadiaConjunto";
	String CD_ESTADIA_CARRETA = "IdEstadiaCarreta";
	String CD_PALETIZACAO = "IDPaletizacao";
	String CD_REEMBOLSO = "IDReembolso";
	String CD_RETORNO_CANHOTO_NF = "IDRetornoCanhotoNF";
	String CD_ENTREGA_COLETA_DEDICADO = "IdEntColDedicado";
	String CD_ENTREGA_COLETA_DEDICADO_KM = "IdEntColDedicadokm";
	String CD_ENTREGA_COLETA_DEDICADO_TOCO = "IdEntColDedToco";
	String CD_ENTREGA_COLETA_DEDICADO_TOCO_KM = "IdEntColDedTocokm";
	String CD_ENTREGA_COLETA_DEDICADO_VAN = "IdEntColDedVan";
	String CD_ENTREGA_COLETA_DEDICADO_VAN_KM = "IdEntColDedVankm";
	String CD_CAPATAZIA = "IdCapatazia";
	String CD_TAXA_FIEL_DEPOSITARIO = "IdTaxaFielDep";
	String CD_GESTAO_OPERACOES_LOGISTICAS =  "IDGestOpLogEmpr";
	String CD_GESTAO_OPERACOES_LOGISTICAS_NO_CLIENTE =  "IDGestOpLogTerc";
	
	
	/* Contantes para os tipos de pedagio */
	List<String> TIPOS_PEDAGIO = Arrays.asList(
				   new String[]{ConstantesExpedicao.CD_PEDAGIO_FRACAO,ConstantesExpedicao.CD_PEDAGIO_POSTO_FRACAO,ConstantesExpedicao.CD_PEDAGIO_DOCUMENTO,ConstantesExpedicao.CD_PEDAGIO_FAIXA_PESO});
	/* Contantes para os tipos de estadia */
	List<String> TIPOS_ESTADIA = Arrays.asList(
			   new String[]{ConstantesExpedicao.CD_ESTADIA_VEICULO,ConstantesExpedicao.CD_ESTADIA_TRUCK,ConstantesExpedicao.CD_ESTADIA_CONJUNTO,ConstantesExpedicao.CD_ESTADIA_CARRETA,ConstantesExpedicao.CD_ESTADIA_34});

	//Tributos
	String CD_COFINS = "CO";
	String CD_SIT_TRIB_ISENTO = "NC";
	String CD_CSLL = "CS";
	String CD_IMPOSTO_DE_RENDA = "IR";
	String CD_INSS = "IN";
	String CD_ISS = "IS";
	String CD_PIS = "PI";
	String TIPO_ICMS = "ICMS";
	String TIPO_ISS = "ISS";

	//Liberacoes
	String LIBERACAO_CLIENTE_EMBARQUE_PROIBIDO = "CP";
	String LIBERACAO_MUNICIPIO_EMBARQUE_PROIBIDO = "MP";
	String LIBERACAO_CALCULO_MANUAL = "CM";
	String LIBERACAO_CALCULO_CORTESIA = "CC";
	String LIBERACAO_VALOR_MERCADORIA = "VM";
	String LIBERACAO_VALOR_FRETE_LIMITE = "VF";
	String LIBERACAO_VALOR_FRETE_MERCADORIA = "FM";
	String LIBERACAO_PESO_LIMITE = "PE";
	String LIBERACAO_DIFERENCA_PESO = "DP";


	//Padroes
	Long ID_DENSIDADE_MERCURIO = LongUtils.ONE;
	String TP_DENSIDADE_PADRAO = "A";
	String TP_EMPRESA_MERCURIO = "M";
	String TP_EMPRESA_CIA_AEREA = "C";
	
	//Volumes nota fiscal
	String TP_VOLUME_MESTRE = "M";
	String TP_VOLUME_UNITARIO = "U";
	String TP_VOLUME_DETALHE = "D";
	
	//Monitoramento descarga
	String NR_FROTA_BALCAO = "Balcao";
	String NR_FROTA_DEVOLUCAO = "DEV";
	String NR_FROTA_SUBSTITUTO = "SUB";
	
	//Tipos Rota Viagem
	String TP_ROTA_VIAGEM_EXPRESSA = "EX";
	String TP_ROTA_VIAGEM_EXPRESSA_CLIENTE = "EC";
	String TP_ROTA_VIAGEM_EVENTUAL = "EV";	
	
	//Código conferencia
	String COD_CONF = "CODCONF";
    String COD_CONF_EDI = "Cod. Conf";
    String COD_CONF_EDI_COM_ACENTO = "Cód. Conf";
	
	//Informações adicionais para o manifesto
	String SPP_NATURA = "SPP Natura Carimbar CTRC e seguir orientações do cliente";
	
	//Numero com as 8 posicoes iniciais de cnpj natura
	String CNPJ_NATURA = "71673990";
	String NM_PARAMETRO_IDS_NATURA = "IDS_NATURA";
	String NM_PARAMETRO_IDS_GM = "IDS_GM";
	String NM_PARAMETRO_DT_IMP_TERRA_NATURA = "DT_IMP_TERRA_NATURA";
	String NM_PARAMETRO_TP_SERVICO_REENTREGA_NATURA = "TP_SERVICO_REENTREGA_NATURA";
	String NM_PARAMETRO_TP_SERVICO_DEVOLUCAO_NATURA = "TP_SERVICO_DEVOLUCAO_NATURA";
	String NM_PARAMETRO_BLQ_COLETA_OUT_ORIG = "BLQ_COLETA_OUT_ORIG";

	String NR_OCORRENCIA_ENTREGA = "NR_OCORRENCIA_ENTREGA";
	
	String CNPJS_CLIENTES_USAM_PEDIDO = "CNPJS_CLIENTES_USAM_PEDIDO";
	String PEDIDO = "PEDIDO";
	String BOX = "Box";

	//Situação Cobrança Docto Serviço
	String DOCTO_SERVICO_LIQUIDADO = "L";

	//Fase Processo
	Short CD_FASE_PROCESSO = 1;
	
	//Localizações Mercadoria
	Short CD_MERCADORIA_NO_TERMINAL = 24;
	Short CD_MERCADORIA_RETORNADA_NO_TERMINAL = 35;
	Short CD_MERCADORIA_REFATURADA = 54;
	Short CD_MERCADORIA_DEVOLVIDA = 53;

	//Ocorrencias Liberação Bloqueio
	Short CD_OCORRENCIA_MERCADORIA_REFATURADA = 93;
	Short CD_OCORRENCIA_MERCADORIA_REFATURADA_LEG = 104;
	
	Short CD_OCORRENCIA_MERCADORIA_DEVOLVIDA = 92;
	Short CD_OCORRENCIA_MERCADORIA_DEVOLVIDA_LEG = 103;
	
	Short CD_OCORRENCIA_LIBERACAO_BLOQUEIO_AGENDAMENTO = 204;
	
	//Ocorrencias Bloqueio
	Short CD_OCORRENCIA_BLOQUEIO_AGENDAMENTO = 203;
	//Tipos de Contatos
	String TIPO_CONTATO_AEREO = "AE";
	
	//Situação do documentos eletrônicos
	String TP_SITUACAO_DOC_ELETRONICO_AUTORIZADO = "A";
	String TP_SITUACAO_DOC_ELETRONICO_ENVIADO = "E";
	String TP_SITUACAO_DOC_ELETRONICO_REJEITADO = "R";
	String TP_SITUACAO_DOC_ELETRONICO_AGUARDA_NRO = "F";
	String TP_SITUACAO_DOC_ELETRONICO_INUT_ENVIADA = "H";
	
	//Tipo Relatorio Controle Carga
	String TP_RELATORIO_CONTROLE_CARGA_COLETA = "C"; 
	String TP_RELATORIO_CONTROLE_CARGA_ENTREGA = "E"; 
	String TP_RELATORIO_CONTROLE_CARGA_VIAGEM = "V"; 

	//Tipo situacao meio transporte
	String TP_RELATORIO_CONTROLE_CARGA_COLETA_AGUARDANDO_SAIDA = "AGSA";
	
	//Campo XML NFE
	String NOME_CAMPO_OBSERVACAO = "NAME";
	
	//Tipo de AWB
	String TP_AWB_NORMAL= "NO";
	String TP_AWB_COMPLEMENTAR= "CO";
	//Situação da Ordem de Serviço
	String TP_SITUACAO_OS_DIGITADA = "D";
	String TP_SITUACAO_OS_APROVADA = "A";
	String TP_SITUACAO_OS_REAPROVADA = "R";
	String TP_SITUACAO_OS_EM_PRE_FATURA = "P";
	
	//Tipo de Documento da Ordem de Serviço
	String TP_DOCUMENTO_DOCTO_SERVICO = "DSE";
	String TP_DOCUMENTO_MANIFESTO_VIAGEM = "MVN";
	String TP_DOCUMENTO_MANIFESTO_ENTREGA = "MEN";
	String TP_DOCUMENTO_MANIFESTO_COLETA = "MCO";
	
	String TP_SITUACAO_DIGITADA = "D";
	String TP_SITUACAO_APROVADA = "A";
	String TP_SITUACAO_REPROVADA = "R";
	
	//TP_INDICADOR DE Serviço Adicional Cliente
	String TP_INDICADOR_POR_VALOR = "V";
	String TP_INDICADOR_POR_DESCONTO = "D";
	String TP_INDICADOR_POR_ACRESCIMO = "A";
	
	//TP_SITUACAO DE Pré Fatura de Serviço
	String TP_SITUACAO_PRE_FATURA_GERADA = "G";
	String TP_SITUACAO_PRE_FATURA_APROVADA = "A";
	String TP_SITUACAO_PRE_FATURA_FINALIZADA = "F";
	
	//TP_SITUACAO DE Item de Pré Fatura de Serviço
	String TP_SITUACAO_ITEM_PRE_FATURA_INFORMADO = "I";
	String TP_SITUACAO_ITEM_PRE_FATURA_APROVADO_COM_DESCONTO = "D";
	String TP_SITUACAO_ITEM_PRE_FATURA_APROVADO = "A";
	String TP_SITUACAO_ITEM_PRE_FATURA_REPROVADO = "R";
	String TP_SITUACAO_ITEM_PRE_FATURA_POSTERGADO = "P";		
	
	//Ação pre-fatura serviços adicionais
	String TP_ACAO_APROVAR_ITEM_PRE_FATURA = "A";
	String TP_ACAO_APROVAR_COM_DESCONTO_ITEM_PRE_FATURA = "D";
	String TP_ACAO_REPROVAR_ITEM_PRE_FATURA = "R";
	String TP_ACAO_POSTERGAR_ITEM_PRE_FATURA = "P";	
	
	//TP_SITUACAO DE Nota Fiscal
	String NOTA_FISCAL_SERVICO_SITUACAO_EMITIDA = "E";
	String NOTA_FISCAL_SERVICO_SITUACAO_GERADA = "G";
	
	//DIVISOES
	String DIVISAO_CENTRO_OESTE_E_NORTE = "Centro-Oeste e Norte";
	
	//Status do Controle de Carga
	String TP_STATUS_CONTROLE_CARGA_AGUARDANDO_SAIDA_ENTREGA = "AE";
	String TP_STATUS_CONTROLE_CARGA_AGUARDANDO_SAIDA_VIAGEM = "AV";
	String TP_STATUS_CONTROLE_CARGA_EM_TRANSITO_PARA_PORTO = "TP";
	
	//Cias Aereas
	String SG_TAM = "TAM";
	String SG_GOL = "GOL";
	String SG_OCE = "OCE";
	String SG_AZU = "AZU";
	
	//Inicio e fim do código da cia aerea
	int COD_CIA_AEREA_INICIO = 0;
	int COD_CIA_AEREA_FIM = 4;
	int NR_AWB_FIM = 10;
	
	String INF_CTE_ID = "//CTe/infCte/@Id";
	String PATH_CODIGO_CIA_AEREA = "//CTe/infCte/infCTeNorm/infModal/aereo/nOCA/text()";
	String DESCRICAO_PARCELA_PADRAO = "FRETE";
	
	String MSG_CIA_NAO_MAPEADA = "LMS-04522";
	String INCLUSAO_XML_AWB = "Inclusão XML AWB";
	String INCLUSAO_PDF_AWB = "Inclusão PDF AWB";
	String INCLUSAO_OUTRO_ANEXO_AWB = "Inclusão Outro Anexo AWB";
	String CANCELAMENTO_XML_AWB = "Cancelamento XML AWB";
	
	String TP_ANEXO_XML = "XML";
	String TP_ANEXO_PDF = "PDF";
	String TP_ANEXO_OUTRO = "";
	
	String SG_ANEXO_XML = "X";
	String SG_ANEXO_PDF = "P";
	String SG_ANEXO_OUTRO = "O";
	
	String MODAL_RODOVIARIO_OBRIGA_BO = "R";
	String MODAL_AEREO_OBRIGA_BO = "A";
	String MODAL_AMBOS_OBRIGA_BO = "T";

	String TIPO_EMPRESA_PARCEIRO = "P";
	
	String ANALITICO_AJUSTADO = "A";
	String ANALITICO_ORIGINAL = "O";

	String TIPO_DOCUMENTO_ANTERIOR = "13";
	String ID_DOCTO_SERVICO = "idDoctoServico";
	String DH_EMISSAO = "dhEmissao";
	String MOEDA_DS_SIMBOLO = "moeda.dsSimbolo";
	String MOEDA_ID_MOEDA = "moeda.idMoeda";
	String VL_TOTAL_DOC_SERVICO = "vlTotalDocServico";
	String SERVICO_TP_MODAL = "servico.tpModal";
	String LOCALIZACAO_MERCADORIA_CD_LOCALIZACAO_MERCADORIA = "localizacaoMercadoria.cdLocalizacaoMercadoria";
	String FILIAL_BY_ID_FILIAL_DESTINO_ID_FILIAL = "filialByIdFilialDestino.idFilial";
	String FILIAL_BY_ID_FILIAL_DESTINO_SG_FILIAL = "filialByIdFilialDestino.sgFilial";
	String CLIENTE_BY_ID_CLIENTE_REMETENTE_ID_CLIENTE = "clienteByIdClienteRemetente.idCliente";
	String CLIENTE_BY_ID_CLIENTE_REMETENTE_PESSOA_NM_PESSOA = "clienteByIdClienteRemetente.pessoa.nmPessoa";
	String CLIENTE_BY_ID_CLIENTE_REMETENTE_PESSOA_NR_IDENTIFICACAO_FORMATADO = "clienteByIdClienteRemetente.pessoa.nrIdentificacaoFormatado";
	String CLIENTE_BY_ID_CLIENTE_DESTINATARIO_ID_CLIENTE = "clienteByIdClienteDestinatario.idCliente";
	String CLIENTE_BY_ID_CLIENTE_REMETENTE_BL_CLIENTE_CCT = "clienteByIdClienteRemetente.blClienteCCT";
	String CLIENTE_BY_ID_CLIENTE_DESTINATARIO_PESSOA_NM_PESSOA = "clienteByIdClienteDestinatario.pessoa.nmPessoa";
	String CLIENTE_BY_ID_CLIENTE_DESTINATARIO_PESSOA_NR_IDENTIFICACAO_FORMATADO = "clienteByIdClienteDestinatario.pessoa.nrIdentificacaoFormatado";
	String CONHECIMENTO_RODOVIARIO_CARGAS_NACIONAL = "CTR";
	String MINUTA_DESPACHO_E_ACOMPANHA = "MDA";

	//Outros
	int MULTIPLICADOR_SINAIS_POSITIVO = 1;
	
	String DM_TP_CARGA_DOCUMENTO_PARCEL = "P";
	String DM_TP_CARGA_DOCUMENTO_FREIGHT = "F";
}
