package com.mercurio.lms.edi.enums;

public enum CampoNotaFiscalEdiComplementoFedex {
	
	AVERBACAO_CTE_FEDEX("AVERBACAO CTE FEDEX"),
	RESPONSAVEL_SEGURO_CTE_FEDEX("RESPONSAVEL SEGURO CTE FEDEX"),
	CNPJ_SEGURADORA_FEDEX("CNPJ SEGURADORA FEDEX"),
	NOME_SEGURADORA_FEDEX("NOME SEGURADORA FEDEX"),
	APOLICE_SEGURO_CTE_FEDEX("APOLICE SEGURO CTE FEDEX"),
	MANIFESTO_FEDEX("MANIFESTO FEDEX"),
    // INTA-379
	CNPJ_REMETENTE_CTE_FEDEX("CNPJ REMETENTE CTE FEDEX"),
	NOME_REMETENTE_CTE_FEDEX("NOME REMETENTE CTE FEDEX"),
    CNPJ_DESTINATARIO_CTE_FEDEX("CNPJ DESTINATARIO CTE FEDEX"),
    NOME_DESTINATARIO_CTE_FEDEX("NOME DESTINATARIO CTE FEDEX"),
    NATUREZA_PRODUTO_FEDEX("NATUREZA PRODUTO FEDEX"),
    // LMSA-6443->LMSA-6451
    PLACA_CARRETA_FEDEX("PLACA CARRETA FEDEX"),
    PLACA_VEICULO_FEDEX("PLACA VEICULO FEDEX"),
    CNPJ_MOTORISTA_FEDEX("CNPJ MOTORISTA FEDEX"),
    NOME_MOTORISTA_FEDEX("NOME MOTORISTA FEDEX"),
    FILIAL_FEDEX_DESTINO_VIAGEM("FILIAL FEDEX DESTINO VIAGEM"),
    TIPO_DOCUMENTO_FEDEX("TIPO DOCUMENTO FEDEX"),
    FILIAL_ORIGEM_CTE_FEDEX("FILIAL ORIGEM CTE FEDEX"),
    FILIAL_DESTINO_CTE_FEDEX("FILIAL DESTINO CTE FEDEX"),
    TIPO_SERVICO_CTE_FEDEX("TIPO SERVICO CTE FEDEX"),
    PESO_AFERIDO_CTE_FEDEX("PESO AFERIDO CTE FEDEX"),
    PESO_AFORADO_CTE_FEDEX("PESO AFORADO CTE FEDEX"),
    PESO_CALCULO_CTE_FEDEX("PESO CALCULO CTE FEDEX"),
    MOEDA_CTE_FEDEX("MOEDA CTE FEDEX"),
    CHAVE_MDFE_FEDEX("CHAVE MDFE FEDEX");
	
	private String nomeCampo;
	
	CampoNotaFiscalEdiComplementoFedex(String nomeCampo) {
		this.nomeCampo = nomeCampo;
	}
	
	public String getNomeCampo() {
		return this.nomeCampo;
	}

}
