package com.mercurio.lms.mww.action;

import java.util.Map;

import com.mercurio.adsm.framework.model.CrudAction;
import com.mercurio.lms.carregamento.model.service.ConferirDispositivoUnitizacaoService;

/**
 * Generated by: ADSM ActionGenerator
 *  
 * Não inserir documentação após ou remover a tag do XDoclet a seguir.
 * O valor do <code>id</code> informado abaixo deve ser utilizado para referenciar este serviço.
 * @spring.bean id="lms.mww.conferirDispositivoUnitizacaoAction"
 */
public class ConferirDispositivoUnitizacaoAction extends CrudAction {
	
	private ConferirDispositivoUnitizacaoService conferirDispositivoUnitizacaoService;
	
	/**
	 * 
	 * @param barCode
	 * @return Map
	 */
	public Map<String, Object> findDispositivoUnitizacaoByBarCode(String barCode){		
		return getConferirDispositivoUnitizacaoService().findDispositivoUnitizacaoByBarCode(barCode);    	
    }
	
	public Map<String, Object> findDispositivoUnitizacaoById(Long idDispositivoUnitizacao){		
		return getConferirDispositivoUnitizacaoService().findDispositivoUnitizacaoById(idDispositivoUnitizacao);    	
    }
	
	public java.io.Serializable executeGeraEventoDispositivoEncontrado(Long idDispsitivoUnitizacao) {
		return conferirDispositivoUnitizacaoService.executeGeraEventoDispositivoEncontrado(idDispsitivoUnitizacao);
	}
	
	public java.io.Serializable executeEventoDispositivoLido(Long idDispsitivoUnitizacao) {
		return conferirDispositivoUnitizacaoService.executeEventoDispositivoLido(idDispsitivoUnitizacao);
	}
	
	public java.io.Serializable executeGeraEventoDispositivoEncontradoTpScan(Long idDispositivo, String TpScan){
		return conferirDispositivoUnitizacaoService.executeGeraEventoDispositivoEncontradoTpScan(idDispositivo, TpScan);
	}

	public java.io.Serializable executeEventoDispositivoLidoTpScan(Long idDispositivo, String TpScan) {
		return conferirDispositivoUnitizacaoService.executeEventoDispositivoLidoTpScan(idDispositivo,TpScan);
	}

	
	public void setConferirDispositivoUnitizacaoService(ConferirDispositivoUnitizacaoService conferirDispositivoUnitizacaoService) {
		this.conferirDispositivoUnitizacaoService = conferirDispositivoUnitizacaoService;
	}
	
	public ConferirDispositivoUnitizacaoService getConferirDispositivoUnitizacaoService() {
		return conferirDispositivoUnitizacaoService;
	}
}
